import { GRADE_PROFILES, type ArithmeticGrade, type MentalStrategy } from "./arithmetic";
export type ArithmeticItem={id:string;grade:ArithmeticGrade;skillId:string;prompt:string;answer:number;strategy:MentalStrategy;expectedMs:number;difficulty:number;meta:Record<string,number|string>};
function rng(seed:number){let a=seed>>>0;return()=>{a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296}}
const pick=<T,>(r:()=>number,x:T[])=>x[Math.floor(r()*x.length)];
const n=(r:()=>number,a:number,b:number)=>Math.floor(r()*(b-a+1))+a;
export function generateArithmeticSet(grade:ArithmeticGrade,count=20,seed=Date.now(),focusSkills:string[]=[],balanced=false):ArithmeticItem[]{const r=rng(seed);const p=GRADE_PROFILES[grade];const bag=p.skills.flatMap(s=>Array.from({length:s.weight*(focusSkills.includes(s.id)?3:1)},()=>s));const balancedSkills=balanced?Array.from({length:count},(_,i)=>p.skills[i%p.skills.length]).sort(()=>r()-.5):[];const out:ArithmeticItem[]=[];
 for(let i=0;i<count;i++){const s=balanced?balancedSkills[i]:pick(r,bag);let prompt="",answer=0,strategy=pick(r,s.strategies),difficulty=1;
 if(grade===1){if(s.id==="number10"){const a=n(r,1,9);prompt=`${a} + □ = 10`;answer=10-a;strategy="make10"}else if(s.id==="add20"){const a=n(r,2,9),b=n(r,2,9);prompt=`${a} + ${b} = ?`;answer=a+b;strategy=a+b>10?"make10":"fact_recall"}else{const a=n(r,11,20),b=n(r,1,9);prompt=`${a} − ${b} = ?`;answer=a-b;strategy=a-b<10?"bridge10":"fact_recall"}}
 else if(grade===2){if(s.id==="times"){const a=n(r,2,9),b=n(r,2,9);prompt=`${a} × ${b} = ?`;answer=a*b;strategy="fact_recall"}else if(s.id==="divide"){const b=n(r,2,9),q=n(r,2,9);prompt=`${b*q} ÷ ${b} = ?`;answer=q;strategy="fact_recall"}else{const a=n(r,20,89),b=n(r,5,39);if(s.id==="sub100"){const x=Math.max(a,b),y=Math.min(a,b);prompt=`${x} − ${y} = ?`;answer=x-y}else{prompt=`${a} + ${b} = ?`;answer=a+b}strategy=(a%10>=8||b%10>=8)?"compensation":"split"}}
 else if(grade===3){if(s.id==="mul1"){const a=n(r,12,49),b=n(r,2,9);prompt=`${a} × ${b} = ?`;answer=a*b;strategy="distributive"}else if(s.id==="div1"){const b=n(r,2,9),q=n(r,4,25);prompt=`${b*q} ÷ ${b} = ?`;answer=q;strategy="split"}else if(s.id==="friendly"){const base=pick(r,[25,50,125]),m=pick(r,[4,8,16]);prompt=`${base} × ${m} = ?`;answer=base*m;strategy="friendly_25_50_125"}else{const a=n(r,120,850),b=pick(r,[20,30,40,50,90,100]);prompt=`${a} + ${b} = ?`;answer=a+b;strategy="place_value"}}
 else if(grade===4){if(s.id==="friendly"){const a=pick(r,[25,50,125]),b=pick(r,[4,8,16,20,40]);prompt=`${a} × ${b} = ?`;answer=a*b;strategy="friendly_25_50_125"}else if(s.id==="div2"){const d=pick(r,[10,20,25,50]),q=n(r,4,40);prompt=`${d*q} ÷ ${d} = ?`;answer=q;strategy="place_value"}else{const a=n(r,12,99),b=pick(r,[9,11,19,21,99,101]);prompt=`${a} × ${b} = ?`;answer=a*b;strategy=b===9||b===11||b===99||b===101?"compensation":"distributive"}}
 else if(grade===5){if(s.id==="decimal"){const a=n(r,10,99)/10,b=n(r,10,99)/10;prompt=`${a.toFixed(1)} + ${b.toFixed(1)} = ?`;answer=+(a+b).toFixed(1);strategy="place_value"}else if(s.id==="fraction"){const d=pick(r,[2,4,5,10]),a=n(r,1,d-1),b=n(r,1,d-1);prompt=`${a}/${d} + ${b}/${d} = ?（填小数）`;answer=(a+b)/d;strategy="fact_recall"}else{const a=pick(r,[2.5,5,12.5,25]),b=pick(r,[4,8,16,20,40]);prompt=`${a} × ${b} = ?`;answer=a*b;strategy="friendly_25_50_125"}}
 else {if(s.id==="percent"){const pct=pick(r,[10,20,25,50,75]),base=pick(r,[40,80,120,160,200]);prompt=`${base} 的 ${pct}% = ?`;answer=base*pct/100;strategy="fact_recall"}else if(s.id==="fraction"){const d=pick(r,[2,3,4,5,6,8]),a=n(r,1,d-1),m=pick(r,[12,18,24,30,36,48]);prompt=`${m} × ${a}/${d} = ?`;answer=m*a/d;strategy="split"}else{const a=pick(r,[25,50,125]),b=pick(r,[8,16,24,32,40]);prompt=`${a} × ${b} = ?`;answer=a*b;strategy="friendly_25_50_125"}}
 difficulty=Math.min(5,1+Math.floor(s.targetMs/2500));out.push({id:`g${grade}-${seed}-${i}`,grade,skillId:s.id,prompt,answer,strategy,expectedMs:s.targetMs,difficulty,meta:{seed,index:i}})}return out;}
