import fs from "node:fs";import path from "node:path";import type { PublicStudent } from "./auth";import { loadExamAttempts,type QuestionBehavior } from "./attempt-store";import { buildTrainingPlan,type ArithmeticSession } from "./arithmetic-analytics";import type { ArithmeticGrade } from "./arithmetic";import { listExamProfiles } from "./question-bank";
export type StudentInsight={kind:"strength"|"watch"|"priority";title:string;evidence:string;action:string};
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
function median(xs:number[]){if(!xs.length)return 0;const a=[...xs].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
const pct=(x:number)=>Math.round(x*100);
function loadArithmetic(userId:string){const file=path.join(process.cwd(),"private","arithmetic","sessions.jsonl");if(!fs.existsSync(file))return[] as ArithmeticSession[];return fs.readFileSync(file,"utf8").split("\n").filter(Boolean).flatMap(line=>{try{const s=JSON.parse(line) as ArithmeticSession;return s.studentId===userId?[s]:[]}catch{return[]}}).slice(-300)}
function metric(key:string,label:string,rows:QuestionBehavior[]){const answered=rows.filter(q=>q.selected!==null);return{key,label,count:rows.length,accuracy:rows.length?rows.filter(q=>q.correct===true).length/rows.length:0,avgSeconds:mean(answered.map(q=>q.dwellMs).filter(Boolean))/1000}}
function band(qs:QuestionBehavior[],points:number){return metric(`points-${points}`,`${points}分题`,qs.filter(q=>q.points===points))}
function matchesGrade(grades:string,grade:number){const g=grades.toLowerCase();if(/^grade\s*2$/.test(g.trim()))return grade===2;const m=g.match(/grades?\s*(\d+)\s*[–-]\s*(\d+)/);if(m)return grade>=Number(m[1])&&grade<=Number(m[2]);return grade>=11&&g.includes("11")}
function matchesGradeBand(band:string|undefined,grade:number){if(!band)return false;if(band==="1-2")return grade>=1&&grade<=2;if(band==="3-4")return grade>=3&&grade<=4;if(band==="5-6")return grade>=5&&grade<=6;if(band==="7-8")return grade>=7&&grade<=8;if(band==="9-10")return grade>=9&&grade<=10;if(band==="11+")return grade>=11;return false}
export function buildStudentAnalytics(user:PublicStudent){
 const allAttempts=loadExamAttempts(user.id),practiceAttempts=allAttempts.filter(a=>a.profile.paperType==="practice"||a.examId.includes("-practice-")),attempts=allAttempts.filter(a=>a.profile.paperType!=="practice"&&!a.examId.includes("-practice-")),qs=attempts.flatMap(a=>a.questions),practiceQs=practiceAttempts.flatMap(a=>a.questions),answered=qs.filter(q=>q.selected!==null);
 const practiceCorrect=practiceQs.filter(q=>q.correct===true).length,practiceByConcept=new Map<string,QuestionBehavior[]>();for(const q of practiceQs){const x=practiceByConcept.get(q.concept)||[];x.push(q);practiceByConcept.set(q.concept,x)}
 const practiceTopics=[...practiceByConcept.entries()].map(([concept,rows])=>({concept,count:rows.length,correct:rows.filter(x=>x.correct===true).length,accuracy:rows.length?rows.filter(x=>x.correct===true).length/rows.length:0})).sort((a,b)=>b.count-a.count||a.accuracy-b.accuracy);
 const correct=qs.filter(q=>q.correct===true).length,wrong=qs.filter(q=>q.correct===false).length,blank=qs.filter(q=>q.correct===null).length;
 const scorePcts=attempts.map(a=>a.grade.maxScore?Math.max(0,a.grade.score/a.grade.maxScore):0),typical=median(answered.map(q=>q.dwellMs).filter(x=>x>0));
 const changed=qs.filter(q=>q.answerChanges>0),correctToWrong=changed.filter(q=>q.correct===false&&q.answerHistory.slice(0,-1).includes(q.correctAnswer)),wrongToCorrect=changed.filter(q=>q.correct===true&&q.answerHistory.slice(0,-1).some(x=>x!==q.correctAnswer));
 const rushedWrong=qs.filter(q=>q.correct===false&&q.dwellMs>0&&typical>0&&q.dwellMs<typical*.45),stuckWrong=qs.filter(q=>q.correct===false&&typical>0&&q.dwellMs>typical*1.8),tabAway=qs.filter(q=>q.tabAwayCount>0);
 const byConcept=new Map<string,QuestionBehavior[]>();for(const q of qs){const x=byConcept.get(q.concept)||[];x.push(q);byConcept.set(q.concept,x)}
 const concepts=[...byConcept.entries()].map(([concept,rows])=>({concept,count:rows.length,correct:rows.filter(x=>x.correct===true).length,accuracy:rows.length?rows.filter(x=>x.correct===true).length/rows.length:0,avgSeconds:mean(rows.map(x=>x.dwellMs).filter(Boolean))/1000})).sort((a,b)=>b.count-a.count);
 const classicDifficulty=[3,4,5].map(p=>band(qs,p));
 const contextual=attempts.flatMap(a=>a.questions.map(q=>({q,competitionId:a.profile.competitionId||(a.examId.startsWith("maa-")?"maa-amc":a.examId.startsWith("au-amc-")?"australian-amc":undefined),formatId:a.profile.formatId||""})));
 const maa=contextual.filter(x=>x.competitionId==="maa-amc");
 const maaRegular=maa.filter(x=>!x.formatId.startsWith("maa-aime")).map(x=>x.q),maaAime=maa.filter(x=>x.formatId.startsWith("maa-aime")).map(x=>x.q);
 const maaDifficulty=[metric("maa-q1-10","MAA Q1–10",maaRegular.filter(q=>q.questionNo<=10)),metric("maa-q11-20","MAA Q11–20",maaRegular.filter(q=>q.questionNo>=11&&q.questionNo<=20)),metric("maa-q21-25","MAA Q21–25",maaRegular.filter(q=>q.questionNo>=21&&q.questionNo<=25)),metric("aime-q1-5","AIME Q1–5",maaAime.filter(q=>q.questionNo<=5)),metric("aime-q6-10","AIME Q6–10",maaAime.filter(q=>q.questionNo>=6&&q.questionNo<=10)),metric("aime-q11-15","AIME Q11–15",maaAime.filter(q=>q.questionNo>=11&&q.questionNo<=15))];
 const difficulty=[...classicDifficulty,...maaDifficulty].filter(x=>x.count>0);
 const phaseRows=attempts.flatMap(a=>a.questions.map(q=>({q,total:a.profile.questionCount})));const phase=(name:string,min:number,max:number)=>{const rows=phaseRows.filter(x=>{const r=x.q.questionNo/Math.max(1,x.total);return r>min&&r<=max}).map(x=>x.q);return{name,count:rows.length,accuracy:rows.length?rows.filter(x=>x.correct===true).length/rows.length:0,avgSeconds:mean(rows.map(x=>x.dwellMs).filter(Boolean))/1000}};const phases=[phase("前1/3",0,1/3),phase("中1/3",1/3,2/3),phase("后1/3",2/3,1)];
 const insights:StudentInsight[]=[];
 if(qs.length<40)insights.push({kind:"watch",title:"画像仍在建立",evidence:`目前只有 ${attempts.length} 套正式模拟、${qs.length} 道题的行为数据。`,action:"至少再完成 2 套完整计时真题后，再把速度和习惯判断作为稳定结论。"});
 if(qs.length>=20&&correct/qs.length>=.85)insights.push({kind:"strength",title:"整体准确性较稳定",evidence:`累计 ${correct}/${qs.length} 题正确（${pct(correct/qs.length)}%）。`,action:"保持完整卷训练，把更多训练量逐步转向高分题和时间管理。"});
 if(qs.length>=20&&blank/qs.length>=.08)insights.push({kind:"priority",title:"空题比例偏高",evidence:`累计空题 ${blank}/${qs.length}（${pct(blank/qs.length)}%）。`,action:"采用两遍法：第一遍做确定题，超过个人阈值先标记跳过，最后统一回收。"});
 if(rushedWrong.length>=3)insights.push({kind:"priority",title:"存在快速失分信号",evidence:`有 ${rushedWrong.length} 道错题的有效停留时间低于个人典型用时的 45%。`,action:"对低分题增加 5–10 秒结构检查：问什么、已知什么、单位和方向是否看全。"});
 if(stuckWrong.length>=3)insights.push({kind:"priority",title:"部分题投入过久仍未得分",evidence:`有 ${stuckWrong.length} 道错题用时超过个人中位用时的 1.8 倍。`,action:"建立跳题阈值，难题先标记，避免单题吞掉整卷时间。"});
 if(changed.length>=5&&correctToWrong.length>wrongToCorrect.length)insights.push({kind:"priority",title:"复查修改目前净收益为负",evidence:`改错→改对 ${wrongToCorrect.length} 题，改对→改错 ${correctToWrong.length} 题。`,action:"复查时只有找到明确证据才改答案，避免因不确定感无依据改动。"});
 if(changed.length>=5&&wrongToCorrect.length>correctToWrong.length)insights.push({kind:"strength",title:"复查能带来净增益",evidence:`改错→改对 ${wrongToCorrect.length} 题，高于改对→改错 ${correctToWrong.length} 题。`,action:"保留标记复查习惯，并继续记录最值得二次检查的题型。"});
 if(tabAway.length>=3)insights.push({kind:"watch",title:"考试中多次离开页面",evidence:`累计 ${tabAway.reduce((n,q)=>n+q.tabAwayCount,0)} 次切出考试页面；离开时长已从做题时间中扣除。`,action:"正式模拟尽量连续完成，让速度画像更接近真实考试。"});
 const generic=new Set(["official_original","Original oficial","official problem"]),weak=concepts.filter(c=>!generic.has(c.concept)&&c.count>=4&&c.accuracy<.65).sort((a,b)=>a.accuracy-b.accuracy).slice(0,3);if(weak.length)insights.push({kind:"priority",title:"稳定失分主题已经出现",evidence:weak.map(c=>`${c.concept} ${c.correct}/${c.count}`).join("；"),action:"下一轮先做同类题短组修准确性，再回完整卷验证迁移。"});
 const easy=classicDifficulty[0],hard=classicDifficulty[2];if(easy.count>=8&&hard.count>=8&&easy.accuracy>=.85&&hard.accuracy<.45)insights.push({kind:"watch",title:"基础题稳定，高分题转化不足",evidence:`3分题 ${pct(easy.accuracy)}%，5分题 ${pct(hard.accuracy)}%。`,action:"减少重复基础题，把专项时间用于建模、分类讨论、空间与组合等高分题。"});
 const maaEasy=maaDifficulty[0],maaHard=maaDifficulty[2];if(maaEasy.count>=8&&maaHard.count>=4&&maaEasy.accuracy>=.85&&maaHard.accuracy<.45)insights.push({kind:"watch",title:"美国 AMC 前段稳定，后段转化不足",evidence:`Q1–10 正确率 ${pct(maaEasy.accuracy)}%，Q21–25 为 ${pct(maaHard.accuracy)}%。`,action:"减少前10题重复刷题，把训练重心移到 Q15–25 的建模、组合、数论与几何综合题，同时保留完整75/40分钟模拟。"});
 if(phases[0].count>=8&&phases[2].count>=8&&phases[0].accuracy-phases[2].accuracy>=.15)insights.push({kind:"watch",title:"后程正确率明显下降",evidence:`前 1/3 正确率 ${pct(phases[0].accuracy)}%，后 1/3 为 ${pct(phases[2].accuracy)}%。`,action:"下一套卷重点控制难题耗时，并预留最后 8–10 分钟复核低分题。"});
 if(attempts.length>=4){const d=mean(scorePcts.slice(-2))-mean(scorePcts.slice(-4,-2));if(d>=.08)insights.push({kind:"strength",title:"近期完整卷表现上行",evidence:`最近 2 套平均得分率较此前 2 套提高 ${Math.round(d*100)} 个百分点。`,action:"换不同年份或赛区继续验证提升是否稳定迁移。"});else if(d<=-.08)insights.push({kind:"watch",title:"近期完整卷出现波动",evidence:`最近 2 套平均得分率较此前 2 套低 ${Math.round(Math.abs(d)*100)} 个百分点。`,action:"先区分难度差异、时间分配和特定题型失分，不用一次波动判断能力下降。"})}
 const arithmetic=loadArithmetic(user.id),arithmeticPlan=user.grade>=1&&user.grade<=6?buildTrainingPlan(user.grade as ArithmeticGrade,arithmetic):null;
 const latest=attempts.slice(-8).map(a=>({id:a.id,examId:a.examId,submittedAt:a.submittedAt,scorePct:a.grade.maxScore?a.grade.score/a.grade.maxScore:0,accuracy:a.questions.length?a.questions.filter(q=>q.correct===true).length/a.questions.length:0,elapsedSeconds:a.elapsedSeconds}));
 const overview={examAttempts:attempts.length,totalQuestions:qs.length,correct,wrong,blank,accuracy:qs.length?correct/qs.length:0,averageScorePct:mean(scorePcts),medianQuestionSeconds:typical/1000,answerChangeRate:qs.length?changed.length/qs.length:0,correctToWrong:correctToWrong.length,wrongToCorrect:wrongToCorrect.length,tabAwayCount:tabAway.reduce((n,q)=>n+q.tabAwayCount,0)};
 const dataConfidence=Math.round(Math.min(100,Math.min(1,qs.length/120)*70+Math.min(1,attempts.length/5)*30));
 const readiness=qs.length>=40&&attempts.length>=2?Math.round(Math.max(0,Math.min(100,overview.accuracy*70+(1-Math.min(.2,blank/Math.max(1,qs.length))/.2)*20+Math.min(1,attempts.length/5)*10))):null;
 const nextPlan=insights.filter(x=>x.kind==="priority").slice(0,3).map(x=>({title:x.title,action:x.action,evidence:x.evidence}));
 if(nextPlan.length<3&&qs.length<40)nextPlan.push({title:"继续建立完整卷基线",action:"再完成 2 套同年级、不同年份的计时真题；不要只做零散题。",evidence:`当前 ${attempts.length} 套完整考试、${qs.length} 道题。`});
 if(nextPlan.length<3&&arithmetic.length===0&&user.grade<=6)nextPlan.push({title:"建立口算速度基线",action:"完成一次 20 题口算诊断，分开测准确率、启动速度、输入执行和巧算识别。",evidence:"目前没有该账号的口算行为数据。"});
 const done=new Set(attempts.map(a=>a.examId));const recommendedExams=listExamProfiles().filter(x=>x.country!=="Mixed"&&x.paperType!=="practice"&&(x.gradeBand?matchesGradeBand(x.gradeBand,user.grade):matchesGrade(x.gradesEn||x.grades,user.grade))&&!done.has(x.id)).sort((a,b)=>(b.year||0)-(a.year||0)).slice(0,3).map(x=>({id:x.id,name:x.nameZh||x.name,year:x.year,country:x.country,questionCount:x.questionCount}));
 return{user,overview,readiness,dataConfidence,trend:latest,difficulty,phases,concepts:concepts.slice(0,20),insights,nextPlan,recommendedExams,practice:{attempts:practiceAttempts.length,questions:practiceQs.length,correct:practiceCorrect,accuracy:practiceQs.length?practiceCorrect/practiceQs.length:0,topics:practiceTopics.slice(0,12)},arithmetic:{sessions:arithmetic.length,plan:arithmeticPlan}};
}
export type StudentAnalytics=ReturnType<typeof buildStudentAnalytics>;
