"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
type Row={id:string;username:string;candidateNo:string;name:string;grade:number;school?:string;active:boolean;summary:{examAttempts:number;totalQuestions:number;accuracy:number;blank:number;medianQuestionSeconds:number;arithmeticSessions:number;priority:string}};
export default function AdminStudents(){
 const[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[show,setShow]=useState(false),[editing,setEditing]=useState<Row|null>(null);
 const load=()=>fetch('/api/admin/students').then(r=>r.json().then(x=>{if(!r.ok)throw new Error(x.error);setRows(x.students||[])})).catch(e=>setError(String(e.message||e)));
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/admin/students',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))}),x=await r.json();if(!r.ok)throw new Error(x.error);e.currentTarget.reset();setShow(false);load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function patch(id:string,body:Record<string,unknown>){setError("");const r=await fetch('/api/admin/students',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...body})}),x=await r.json();if(!r.ok){setError(x.error||'更新失败');return false}load();return true}
 async function saveEdit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const fd=new FormData(e.currentTarget);const ok=await patch(editing.id,{name:fd.get('name'),grade:Number(fd.get('grade')),school:fd.get('school')});if(ok)setEditing(null);setBusy(false)}
 function resetPin(x:Row){const pin=window.prompt(`为 ${x.name} 设置新 PIN（至少4位）`);if(pin&&pin.length>=4)void patch(x.id,{pin})}
 function toggle(x:Row){if(window.confirm(`${x.active?'停用':'启用'} ${x.name} 的账号？`))void patch(x.id,{active:!x.active})}
 return <div className="admin-shell"><section className="section-heading"><div><span className="eyebrow">STUDENT OPERATIONS</span><h1>学生账号与画像</h1><p>账号、正式模拟、口算训练和行为画像统一到一个学生 ID。</p></div><button className="primary-button" onClick={()=>setShow(x=>!x)}>+ 创建学生</button></section>{error&&<div className="warning-box">{error}</div>}
 {show&&<form className="student-create-form" onSubmit={create}><input name="name" required placeholder="学生姓名"/><input name="username" required placeholder="登录用户名"/><input name="candidateNo" required placeholder="准考证号"/><input name="grade" type="number" min="1" max="13" required placeholder="年级"/><input name="school" placeholder="学校（可选）"/><input name="pin" type="password" required minLength={4} placeholder="初始 PIN"/><button className="primary-button" disabled={busy}>{busy?'创建中…':'创建账号'}</button></form>}
 {editing&&<form className="student-edit-form" onSubmit={saveEdit}><div><span className="eyebrow">EDIT STUDENT</span><h2>编辑 {editing.name}</h2><p>{editing.candidateNo} · 登录名 {editing.username}</p></div><input name="name" required defaultValue={editing.name} placeholder="学生姓名"/><input name="grade" type="number" min="1" max="13" required defaultValue={editing.grade}/><input name="school" defaultValue={editing.school||''} placeholder="学校（可选）"/><div className="student-edit-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>取消</button><button className="primary-button" disabled={busy}>保存资料</button></div></form>}
 <div className="student-admin-table"><div className="student-admin-row head"><span>学生</span><span>年级</span><span>正式模拟</span><span>正确率</span><span>口算</span><span>建议 / 操作</span></div>{rows.map(x=><div className={`student-admin-row ${x.active?'':'disabled'}`} key={x.id}><span><b>{x.name}</b><small>{x.candidateNo} · {x.username}{x.active?'':' · 已停用'}</small></span><span>{x.grade}</span><span>{x.summary.examAttempts} 套<small>{x.summary.totalQuestions} 题</small></span><span>{x.summary.totalQuestions?`${Math.round(x.summary.accuracy*100)}%`:'—'}<small>空 {x.summary.blank}</small></span><span>{x.summary.arithmeticSessions} 轮<small>{x.summary.medianQuestionSeconds?`正式题中位 ${x.summary.medianQuestionSeconds.toFixed(1)}s`:''}</small></span><span><b>{x.summary.priority}</b><small className="student-admin-actions"><Link href={`/admin/students/${x.id}`}>详细画像</Link><button onClick={()=>setEditing(x)}>编辑资料</button><button onClick={()=>resetPin(x)}>重置 PIN</button><button onClick={()=>toggle(x)}>{x.active?'停用':'启用'}</button></small></span></div>)}</div>
 </div>
}
