"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { CLEVER_NODE_GUIDE,GRADE_PROFILES,STRATEGY_GUIDE,type ArithmeticGrade } from "@/lib/arithmetic";
import { buildTrainingPlan,type ArithmeticSession } from "@/lib/arithmetic-analytics";
import { buildLearnerProfile,type LearnerSignal } from "@/lib/math-engine";
export default function ArithmeticDashboard({user}:{user:{id:string;name:string;candidateNo:string;grade:number}}){const [sessions,setSessions]=useState<ArithmeticSession[]>([]);const [signals,setSignals]=useState<LearnerSignal[]>([]);const [selected,setSelected]=useState<ArithmeticGrade>(Math.min(6,Math.max(1,user.grade)) as ArithmeticGrade);
 useEffect(()=>{fetch(`/api/arithmetic/sessions`).then(r=>r.json()).then(x=>setSessions(x.sessions||[])).catch(()=>setSessions([]));},[]);
 useEffect(()=>{fetch(`/api/math-engine/signals?grade=${selected}`).then(r=>r.json()).then(x=>setSignals(x.signals||[])).catch(()=>setSignals([]));},[selected]);
 const p=GRADE_PROFILES[selected],plan=buildTrainingPlan(selected,sessions),mathProfile=buildLearnerProfile(signals);const gradeSessions=sessions.filter(s=>s.grade===selected);const attempts=gradeSessions.flatMap(s=>s.attempts);const accuracy=attempts.length?attempts.filter(a=>a.correct).length/attempts.length:0;
 return <div className="home-shell arithmetic-home"><section className="hero-card arithmetic-hero"><div className="eyebrow">智能口算训练</div><h1>口算诊断<br/><span>与智能训练</span></h1><p className="hero-copy">不是单纯刷题。系统同时分析正确率、启动速度、总耗时、修改/退格行为、错误类型和巧算结构识别，用下一轮最小必要题量修复最值得修复的问题。</p></section>
 <section className="training-launchpad"><div className="training-launchpad-head"><div><span className="eyebrow">训练模式中心</span><h2>现在开始练</h2><p>当前 {selected} 年级 · {p.titleZh}</p></div><div className="grade-switcher" aria-label="选择年级">{([1,2,3,4,5,6] as ArithmeticGrade[]).map(g=><button key={g} type="button" className={selected===g?"active":""} onClick={()=>setSelected(g)}>{g}<small>年级</small></button>)}</div></div><div className="training-primary-grid"><Link className="training-mode-card training-mode-card--adaptive" href={`/arithmetic/session/${selected}?mode=adaptive`}><div className="training-mode-top"><span className="training-mode-number">01</span><em>AI 推荐</em></div><h3>智能训练</h3><p>根据你的最近表现，自动挑选最值得练的题和最小必要题量。</p><strong>开始智能训练 <span>→</span></strong></Link><Link className="training-mode-card training-mode-card--guided" href={`/arithmetic/session/${selected}?mode=guided`}><div className="training-mode-top"><span className="training-mode-number">02</span><em>学方法</em></div><h3>跟我算</h3><p>分层提示、逐步撤掉支架，把“老师带着会”练成自己独立会。</p><strong>开始引导训练 <span>→</span></strong></Link><Link className="training-mode-card training-mode-card--discovery" href={`/arithmetic/discovery/${selected}`}><div className="training-mode-top"><span className="training-mode-number">03</span><em>练眼力</em></div><h3>先别算</h3><p>先观察结构、比较变形，再决定怎么计算，训练真正的数感与策略选择。</p><strong>开始结构发现 <span>→</span></strong></Link></div><div className="training-tool-row"><Link href={`/arithmetic/session/${selected}?mode=diagnostic`}><span>诊断</span><b>{attempts.length?"重新诊断":"20题基线诊断"}</b><small>更新能力基线</small></Link><Link href={`/arithmetic/session/${selected}?mode=speed`}><span>速度</span><b>极速练</b><small>提高自动化与反应速度</small></Link><Link href={`/arithmetic/print?grade=${selected}`}><span>纸笔</span><b>A4 口算</b><small>批量生成打印练习</small></Link></div></section>
 <section className="student-profile-strip"><div><span className="eyebrow">学生画像</span><h2>{user.name} · {user.candidateNo}</h2><p>正式模拟、口算速度、错因与训练历史统一进入同一个个人学习档案。</p></div><Link className="secondary-button" href="/student">查看完整学习报告</Link></section>
 <section className="report-card cognitive-profile-card" style={{marginTop:18}}><div className="cognitive-profile-head"><div><span className="eyebrow">数学认知画像 · 新引擎</span><h2>结构与策略行为证据</h2><p>这里只展示已经被行为数据观测到的能力，不根据单次答题猜测“天赋”或“理解力”。</p></div><div className="evidence-badge"><strong>{signals.length}</strong><span>条证据</span><small>置信 {mathProfile.strategyEvidence.evidence}%</small></div></div><div className="cognitive-bars">{[["结构/策略",mathProfile.strategyEvidence.score,"是否主动利用结构"],["独立完成",mathProfile.independence.score,"是否减少提示依赖"],["提示依赖",mathProfile.hintReliance.score,"越低越独立"],["自动化",mathProfile.fluency.score,"正确且快速稳定"]].map(([label,value,note])=><div className="cognitive-bar-row" key={String(label)}><div><b>{label}</b><small>{note}</small></div><div className="cognitive-bar-track"><i style={{width:value===null?"0%":`${value}%`}}/></div><strong>{value===null?"—":`${value}%`}</strong></div>)}</div></section>
 <section className="arithmetic-dashboard-grid"><article className="report-card"><span className="eyebrow">{p.titleZh}</span><h2>本年级训练标准</h2><div className="target-strip"><div><strong>{Math.round(p.targetAccuracy*100)}%</strong><span>目标正确率</span></div><div><strong>{(p.targetMedianMs/1000).toFixed(1)}s</strong><span>目标中位用时</span></div><div><strong>{gradeSessions.length}</strong><span>已完成训练</span></div></div><div className="skill-list">{p.skills.map(s=><div key={s.id}><b>{s.labelZh}</b><span>目标 {(s.targetMs/1000).toFixed(1)}s · {s.strategies.join(' / ')}</span></div>)}</div></article>
 <article className="report-card"><span className="eyebrow">个性化模型</span><h2>{attempts.length?"当前个人训练建议":"先建立个人基线"}</h2>{attempts.length?<><p className="big-accuracy">{(accuracy*100).toFixed(0)}%</p>{plan.summaryZh.map((x,i)=><p key={i}>{x}</p>)}<div className="focus-chips">{plan.focusSkills.map(id=><span key={id}>{p.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></>:<p>第一次先做20题诊断。系统会建立每个技能的“准确性 × 流畅度 × 稳定性 × 策略效率”基线，再决定下一轮训练内容。</p>}</article></section>
 {attempts.length>0&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">能力画像</span><h2>四维技能画像</h2><p>把每个技能拆成准确性、流畅度、稳定性和策略效率。灰色表示证据不足，不强行下结论。</p></div><div className="analysis-legend"><span><i className="good"/>稳定</span><span><i className="watch"/>需关注</span><span><i/>证据不足</span></div></div><div className="skill-visual-list">{plan.metrics.map(m=>{const skill=p.skills.find(x=>x.id===m.skillId);const scores=[["准",m.accuracyScore],["快",m.fluencyScore],["稳",m.stabilityScore],["巧",m.strategyScore]] as const;return <article className="skill-visual-row" key={m.skillId}><div className="skill-visual-label"><b>{skill?.labelZh||m.skillId}</b><span>{m.attempts} 题 · 证据 {m.evidence}%</span><small>{m.attempts===0?"尚无样本":m.medianMs>(skill?.targetMs||0)?`启动 ${(m.medianMs/1000).toFixed(1)}s · 下一步 ≤ ${(m.personalTargetMs/1000).toFixed(1)}s`:`启动 ${(m.medianMs/1000).toFixed(1)}s · 达到年级速度参考`}</small></div><div className="skill-score-grid">{scores.map(([label,value])=><div className={`skill-score ${value===null?"empty":value>=85?"good":value<70?"watch":""}`} key={label}><span>{label}</span><div><i style={{width:value===null?"0%":`${value}%`}}/></div><strong>{value===null?"—":value}</strong></div>)}</div></article>})}</div></section>}
 {attempts.length>0&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">结构能力</span><h2>巧算能力树</h2><p>颜色直接表示当前状态；证据条越长，结论越可靠。系统下一轮优先处理橙色节点。</p></div>{plan.focusNodes.length>0&&<div className="focus-summary"><small>下一轮优先</small><strong>{plan.focusNodes.map(x=>CLEVER_NODE_GUIDE[x].zh).join(" · ")}</strong></div>}</div><div className="ability-node-grid">{plan.nodeMetrics.map(m=>{const status=m.status==="mastered"?"good":m.status==="needs_accuracy"||m.status==="needs_fluency"?"watch":m.status==="monitor"?"monitor":"empty";const statusText=m.status==="mastered"?"稳定":m.status==="needs_accuracy"?"补准确":m.status==="needs_fluency"?"提速度":m.status==="monitor"?"复测":"样本少";return <article className={`ability-node ${status}`} key={m.node}><header><b>{CLEVER_NODE_GUIDE[m.node].zh}</b><span>{statusText}</span></header><div className="ability-node-main"><strong>{m.attempts?Math.round(m.correct/m.attempts*100):0}%</strong><small>正确率</small><em>{m.attempts}题</em></div><div className="evidence-track"><i style={{width:`${m.evidence}%`}}/></div><footer><span>证据 {m.evidence}%</span><span>{m.attempts?`启动 ${(m.medianMs/1000).toFixed(1)}s`:"待采样"}</span></footer></article>})}</div></section>}
 {attempts.length>0&&plan.probeMetrics.length>0&&<section className="analysis-section compact-analysis"><div className="analysis-section-head"><div><span className="eyebrow">诊断探针</span><h2>慢在哪里？</h2><p>用相似题对照，区分“基础算力慢”和“没有及时发现结构”。</p></div></div><div className="probe-list">{plan.probeMetrics.map(m=><article key={m.node}><div><b>{CLEVER_NODE_GUIDE[m.node].zh}</b><span>{m.pairs} 组对照</span></div><div className="probe-ratio"><span>普通 {(m.controlMedianMs/1000).toFixed(1)}s</span><i><b style={{width:`${Math.min(100,Math.max(8,m.slowdownRatio*50))}%`}}/></i><span>巧算 {(m.strategyMedianMs/1000).toFixed(1)}s</span></div><strong className={`probe-status ${m.status}`}>{m.status==="strategy_gap"?"结构识别缺口":m.status==="general_slow"?"基础流畅度偏慢":m.status==="monitor"?"继续观察":m.status==="efficient"?"策略识别正常":"样本不足"}</strong></article>)}</div></section>}
 {attempts.length>0&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">策略画像</span><h2>哪些方法已经变成习惯？</h2><p>不再堆文字：直接看正确率、启动速度和证据量。</p></div></div><div className="strategy-visual-list">{plan.strategyMetrics.map(m=>{const pct=m.attempts?Math.round(m.correct/m.attempts*100):0;const status=m.status==="mastered"?"good":m.status==="needs_accuracy"||m.status==="needs_fluency"?"watch":m.status==="monitor"?"monitor":"empty";return <article className={`strategy-visual-row ${status}`} key={m.strategy}><div className="strategy-title"><b>{STRATEGY_GUIDE[m.strategy].zh}</b><span>{m.attempts}题 · 证据 {m.evidence}%</span></div><div className="strategy-bar"><i style={{width:`${pct}%`}}/></div><strong>{m.attempts?`${pct}%`:"—"}</strong><small>{m.attempts?`${(m.medianMs/1000).toFixed(1)}s`:"待采样"}</small></article>})}</div></section>}
 </div>}
