"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { GRADE_PROFILES,type ArithmeticGrade } from "@/lib/arithmetic";
import { buildTrainingPlan,type ArithmeticSession } from "@/lib/arithmetic-analytics";
export default function ArithmeticDashboard(){const [sessions,setSessions]=useState<ArithmeticSession[]>([]);const [selected,setSelected]=useState<ArithmeticGrade>(1);
 useEffect(()=>{fetch('/api/arithmetic/sessions').then(r=>r.json()).then(x=>setSessions(x.sessions||[])).catch(()=>{});},[]);
 const p=GRADE_PROFILES[selected],plan=buildTrainingPlan(selected,sessions);const gradeSessions=sessions.filter(s=>s.grade===selected);const attempts=gradeSessions.flatMap(s=>s.attempts);const accuracy=attempts.length?attempts.filter(a=>a.correct).length/attempts.length:0;
 return <div className="home-shell arithmetic-home"><section className="hero-card arithmetic-hero"><div className="eyebrow">ADAPTIVE MENTAL MATH</div><h1>口算诊断<br/><span>与智能训练</span></h1><p className="hero-copy">不是单纯刷题。系统同时分析正确率、启动速度、总耗时、修改/退格行为、错误类型和巧算结构识别，用下一轮最小必要题量修复最值得修复的问题。</p></section>
 <section className="section-heading"><div><span className="eyebrow">GRADE PROFILES</span><h1>选择年级</h1><p>每个年级有不同的技能范围、速度目标和巧算策略。</p></div></section>
 <div className="grade-profile-grid">{([1,2,3,4,5,6] as ArithmeticGrade[]).map(g=>{const x=GRADE_PROFILES[g];return <button key={g} className={`grade-profile-card ${selected===g?'active':''}`} onClick={()=>setSelected(g)}><strong>{g}</strong><span>年级</span><small>{x.skills.map(s=>s.labelZh).slice(0,2).join(' · ')}</small></button>})}</div>
 <section className="arithmetic-dashboard-grid"><article className="report-card"><span className="eyebrow">{p.titleZh}</span><h2>本年级训练标准</h2><div className="target-strip"><div><strong>{Math.round(p.targetAccuracy*100)}%</strong><span>目标正确率</span></div><div><strong>{(p.targetMedianMs/1000).toFixed(1)}s</strong><span>目标中位用时</span></div><div><strong>{gradeSessions.length}</strong><span>已完成训练</span></div></div><div className="skill-list">{p.skills.map(s=><div key={s.id}><b>{s.labelZh}</b><span>目标 {(s.targetMs/1000).toFixed(1)}s · {s.strategies.join(' / ')}</span></div>)}</div></article>
 <article className="report-card"><span className="eyebrow">PERSONAL MODEL</span><h2>{attempts.length?"当前个人训练建议":"先建立个人基线"}</h2>{attempts.length?<><p className="big-accuracy">{(accuracy*100).toFixed(0)}%</p>{plan.summaryZh.map((x,i)=><p key={i}>{x}</p>)}<div className="focus-chips">{plan.focusSkills.map(id=><span key={id}>{p.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></>:<p>第一次先做20题诊断。系统会建立每个技能的“正确率 × 速度 × 犹豫 × 修改”基线，再决定下一轮训练内容。</p>}<div className="hero-actions arithmetic-actions"><Link className="secondary-button" href={`/arithmetic/session/${selected}?mode=diagnostic`}>{attempts.length?"重新诊断":"开始20题诊断"}</Link><Link className="primary-button" href={`/arithmetic/session/${selected}?mode=adaptive`}>开始智能训练</Link></div></article></section>
 {attempts.length>0&&<section className="report-card arithmetic-metrics"><h2>技能画像</h2>{plan.metrics.map(m=>{const s=p.skills.find(x=>x.id===m.skillId);return <div className="metric-row arithmetic-metric" key={m.skillId}><span>{s?.labelZh||m.skillId}</span><div className="metric-bar"><i style={{width:`${Math.min(100,m.accuracy*100)}%`}}/></div><strong>{m.attempts?`${Math.round(m.accuracy*100)}%`:'—'}</strong><small>{m.attempts?`${(m.medianMs/1000).toFixed(1)}s`:'待测'}</small></div>})}</section>}
 </div>}
