"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { GRADE_PROFILES,STRATEGY_GUIDE,type ArithmeticGrade } from "@/lib/arithmetic";
import { generateArithmeticSet,type ArithmeticItem } from "@/lib/arithmetic-generator";
import { buildTrainingPlan,finalizeAttempt,type ArithmeticAttempt,type ArithmeticSession,type ErrorReason,type TrainingPlan } from "@/lib/arithmetic-analytics";

type Mode="diagnostic"|"adaptive"|"speed";
const REASON_ZH:Record<ErrorReason,string>={correct:"正确",slow_recall:"事实提取偏慢",impulsive:"出手过快",hesitation:"犹豫/反复修改",near_miss:"接近正确/注意力",operation_confusion:"运算符混淆",place_value:"位值/进退位",fact_gap:"基础事实不牢",strategy_missed:"未识别巧算结构",unknown:"待进一步判断"};
export default function ArithmeticSessionClient({grade,mode,seed}:{grade:ArithmeticGrade;mode:Mode;seed:number}){
 const profile=GRADE_PROFILES[grade];const [items,setItems]=useState<ArithmeticItem[]|null>(null);const [history,setHistory]=useState<ArithmeticSession[]>([]);const [idx,setIdx]=useState(0);const [raw,setRaw]=useState("");const [attempts,setAttempts]=useState<ArithmeticAttempt[]>([]);const [edits,setEdits]=useState(0);const [backspaces,setBackspaces]=useState(0);const [done,setDone]=useState<TrainingPlan|null>(null);const [saving,setSaving]=useState(false);const [feedback,setFeedback]=useState<ArithmeticAttempt|null>(null);const [repairs,setRepairs]=useState(0);
 const presentedAt=useRef(0);const firstInputAt=useRef<number|null>(null);const inputRef=useRef<HTMLInputElement>(null);const sessionSeed=useRef(seed);
 useEffect(()=>{const activeSeed=seed||Math.floor(performance.now()*100000);sessionSeed.current=activeSeed;fetch('/api/arithmetic/sessions').then(r=>r.json()).then(data=>{const old=(data.sessions||[]) as ArithmeticSession[];setHistory(old);const focus=mode==='adaptive'?buildTrainingPlan(grade,old).focusSkills:[];setItems(generateArithmeticSet(grade,mode==='diagnostic'?20:mode==='speed'?60:30,activeSeed,focus));setTimeout(()=>inputRef.current?.focus(),0)}).catch(()=>setItems(generateArithmeticSet(grade,mode==='diagnostic'?20:mode==='speed'?60:30,activeSeed)));},[grade,mode,seed]);
 useEffect(()=>{if(items&&presentedAt.current===0)presentedAt.current=performance.now()},[items]);
 if(!items)return <div className="center-card"><div className="loader"/><h2>正在读取个人训练模型…</h2><p>加载历史正确率、速度与错误习惯。</p></div>;
 const item=items[idx];
 const resetForNext=()=>{setRaw("");setEdits(0);setBackspaces(0);setFeedback(null);firstInputAt.current=null;presentedAt.current=performance.now();setTimeout(()=>inputRef.current?.focus(),0)};
 const finish=async(all:ArithmeticAttempt[])=>{const session:ArithmeticSession={id:`arith-g${grade}-${sessionSeed.current}-${mode}`,grade,mode,startedAt:Date.now()-all.reduce((s,a)=>s+a.responseMs,0),finishedAt:Date.now(),attempts:all};setSaving(true);try{await fetch('/api/arithmetic/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(session)})}catch{}const next=[...history,session];try{localStorage.setItem('kangaroo-arithmetic-last',JSON.stringify(session))}catch{}setHistory(next);setDone(buildTrainingPlan(grade,next));setSaving(false)};
 const advance=(all:ArithmeticAttempt[])=>{if(idx>=items.length-1){void finish(all)}else{setIdx(x=>x+1);resetForNext()}};
 const submit=()=>{if(!raw.trim()||done||feedback)return;const now=performance.now();const a=finalizeAttempt(item,raw,{presentedAt:presentedAt.current||now,firstInputAt:firstInputAt.current,submittedAt:now,edits,backspaces});const all=[...attempts,a];setAttempts(all);const needsRepair=mode==='adaptive'&&(!a.correct||a.reason==='strategy_missed'||a.reason==='slow_recall');if(needsRepair&&repairs<6){const repair=generateArithmeticSet(grade,1,sessionSeed.current+1000+idx,[item.skillId])[0];setItems(xs=>{if(!xs)return xs;const copy=[...xs];const at=Math.min(copy.length,idx+3);copy.splice(at,0,repair);return copy});setRepairs(x=>x+1)}if(mode==='adaptive'&&(!a.correct||a.reason!=='correct'))setFeedback(a);else advance(all)};
 if(done){const last=attempts;const correct=last.filter(a=>a.correct).length;const med=[...last.map(a=>a.responseMs)].sort((a,b)=>a-b)[Math.floor(last.length/2)]||0;const reasons=Object.entries(last.reduce((m,a)=>{if(!a.correct||a.reason!=="correct")m[a.reason]=(m[a.reason]||0)+1;return m},{ } as Record<string,number>)).sort((a,b)=>b[1]-a[1]);return <div className="report-shell arithmetic-result"><section className="score-hero"><div><span className="eyebrow">{profile.titleZh} · PERSONAL DIAGNOSIS</span><h1>{mode==='diagnostic'?'诊断完成':'训练完成'}</h1><p>{saving?'正在保存学习数据…':'本次行为数据已写入个人模型'}</p></div><div className="score-ring"><strong>{correct}</strong><span>/ {last.length}</span><small>{Math.round(correct/last.length*100)}%</small></div></section><section className="result-stats"><article><strong>{(med/1000).toFixed(1)}s</strong><span>中位用时</span></article><article><strong>{last.filter(a=>a.reason==='impulsive').length}</strong><span>冲动型错误</span></article><article><strong>{last.filter(a=>a.reason==='strategy_missed'||a.reason==='slow_recall').length}</strong><span>效率问题</span></article></section><section className="arithmetic-dashboard-grid"><article className="report-card"><h2>错因与习惯</h2>{reasons.length?reasons.slice(0,6).map(([r,c])=><div className="diagnosis-row" key={r}><span>{REASON_ZH[r as ErrorReason]||r}</span><strong>{c}题</strong></div>):<p>本轮没有明显错误模式。</p>}</article><article className="report-card"><h2>下一轮怎么练</h2>{done.summaryZh.map((x,i)=><p key={i}>{x}</p>)}<div className="focus-chips">{done.focusSkills.map(id=><span key={id}>{profile.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></article></section><div className="report-actions"><Link className="primary-button" href={`/arithmetic/session/${grade}?mode=adaptive`}>立即开始个性化下一轮</Link><Link className="secondary-button" href="/arithmetic">返回口算中心</Link></div></div>}
 return <div className="mental-shell"><section className="mental-topbar"><div><span className="eyebrow">{profile.titleZh}</span><strong>{mode==='diagnostic'?'20题基线诊断':mode==='speed'?'速度挑战':'个性化智能训练'}</strong></div><div className="mental-progress"><span>{idx+1}</span> / {items.length}<i><b style={{width:`${(idx/items.length)*100}%`}}/></i></div><Link className="ghost-button" href="/arithmetic">退出</Link></section><section className="mental-card"><div className="mental-meta"><span>{profile.skills.find(s=>s.id===item.skillId)?.labelZh}</span><small>目标 ≤ {(item.expectedMs/1000).toFixed(1)}s</small></div><div className="mental-prompt">{item.prompt}</div><form onSubmit={e=>{e.preventDefault();submit()}}><input ref={inputRef} className="mental-input" inputMode="decimal" autoComplete="off" value={raw} onKeyDown={e=>{if(e.key==='Backspace')setBackspaces(x=>x+1)}} onChange={e=>{if(firstInputAt.current===null&&e.target.value!=="")firstInputAt.current=performance.now();setEdits(x=>x+1);setRaw(e.target.value)}} placeholder="输入答案"/><button className="primary-button mental-submit" type="submit" disabled={!raw.trim()}>确定 ↵</button></form>{feedback&&<div className={`mental-feedback ${feedback.correct?'ok':'bad'}`}><strong>{feedback.correct?'✓ 答对了':`✕ 正确答案：${feedback.item.answer}`}</strong><p>{REASON_ZH[feedback.reason]} · {STRATEGY_GUIDE[feedback.item.strategy].zh}</p><button className="secondary-button" onClick={()=>advance(attempts)}>继续下一题</button></div>}<div className="mental-hint">请心算，不写竖式。系统会记录你的启动时间、总耗时和修改行为。</div></section></div>;
}
