"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import { GRADE_PROFILES,STRATEGY_GUIDE,type ArithmeticGrade } from "@/lib/arithmetic";
import { generateArithmeticSet,type ArithmeticItem } from "@/lib/arithmetic-generator";
import { buildTrainingPlan,finalizeAttempt,type ArithmeticAttempt,type ArithmeticSession,type ErrorReason,type TrainingPlan } from "@/lib/arithmetic-analytics";

type Mode="diagnostic"|"adaptive"|"speed";
const REASON_ZH:Record<ErrorReason,string>={correct:"正确",slow_recall:"事实提取偏慢",impulsive:"出手过快",hesitation:"犹豫/反复修改",near_miss:"接近正确/注意力",operation_confusion:"运算符混淆",place_value:"位值/进退位",fact_gap:"基础事实不牢",strategy_missed:"未识别巧算结构",unknown:"待进一步判断"};
export default function ArithmeticSessionClient({grade,mode,seed,studentId}:{grade:ArithmeticGrade;mode:Mode;seed:number;studentId:string}){
 const profile=GRADE_PROFILES[grade];const [items,setItems]=useState<ArithmeticItem[]|null>(null);const [history,setHistory]=useState<ArithmeticSession[]>([]);const [idx,setIdx]=useState(0);const [raw,setRaw]=useState("");const [attempts,setAttempts]=useState<ArithmeticAttempt[]>([]);const [edits,setEdits]=useState(0);const [backspaces,setBackspaces]=useState(0);const [done,setDone]=useState<TrainingPlan|null>(null);const [saving,setSaving]=useState(false);const [feedback,setFeedback]=useState<ArithmeticAttempt|null>(null);const [repairs,setRepairs]=useState(0);const [touch]=useState(()=>typeof window!=="undefined"&&window.matchMedia("(pointer: coarse)").matches);
 const presentedAt=useRef(0);const firstInputAt=useRef<number|null>(null);const inputRef=useRef<HTMLInputElement>(null);const sessionSeed=useRef(seed);
 useEffect(()=>{const activeSeed=seed||Math.floor(performance.now()*100000);sessionSeed.current=activeSeed;fetch(`/api/arithmetic/sessions?studentId=${encodeURIComponent(studentId)}`).then(r=>r.json()).then(data=>{const old=(data.sessions||[]) as ArithmeticSession[];setHistory(old);const plan=mode==='adaptive'?buildTrainingPlan(grade,old):null;const focus=plan?.focusSkills||[];const count=mode==='diagnostic'?20:mode==='speed'?60:focus.length===0?12:focus.length===1?16:20;let generated=generateArithmeticSet(grade,count,activeSeed,focus,mode==='diagnostic',plan?.focusNodes||[]);if(plan)generated=generated.map(item=>({...item,expectedMs:plan.metrics.find(m=>m.skillId===item.skillId)?.personalTargetMs||item.expectedMs}));setItems(generated);setTimeout(()=>inputRef.current?.focus(),0)}).catch(()=>setItems(generateArithmeticSet(grade,mode==='diagnostic'?20:mode==='speed'?60:12,activeSeed,[],mode==='diagnostic')));},[grade,mode,seed,studentId]);
 useEffect(()=>{if(items&&presentedAt.current===0)presentedAt.current=performance.now()},[items]);
 if(!items)return <div className="center-card"><div className="loader"/><h2>正在读取个人训练模型…</h2><p>加载历史正确率、速度与错误习惯。</p></div>;
 const item=items[idx];
 const resetForNext=(ts:number)=>{setRaw("");setEdits(0);setBackspaces(0);setFeedback(null);firstInputAt.current=null;presentedAt.current=ts;setTimeout(()=>inputRef.current?.focus(),0)};
 const finish=async(all:ArithmeticAttempt[],ts:number)=>{const finishedAt=performance.timeOrigin+ts;const session:ArithmeticSession={id:`arith-${studentId}-g${grade}-${sessionSeed.current}-${mode}`,studentId,grade,mode,startedAt:finishedAt-all.reduce((sum,a)=>sum+a.responseMs,0),finishedAt,attempts:all};setSaving(true);try{await fetch('/api/arithmetic/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(session)})}catch{}const next=[...history,session];try{localStorage.setItem(`kangaroo-arithmetic-last-${studentId}`,JSON.stringify(session))}catch{}setHistory(next);setDone(buildTrainingPlan(grade,next));setSaving(false)};
 const advance=(all:ArithmeticAttempt[],ts:number)=>{if(idx>=items.length-1){void finish(all,ts)}else{setIdx(x=>x+1);resetForNext(ts)}};
 const noteFirstInput=(ts:number)=>{if(firstInputAt.current===null)firstInputAt.current=ts};
 const pushChar=(ch:string,ts:number)=>{if(ch==='.'&&raw.includes('.'))return;if(raw.length>=8)return;noteFirstInput(ts);setRaw(v=>v+ch)};
 const erase=()=>{if(!raw)return;setBackspaces(x=>x+1);setRaw(v=>v.slice(0,-1))};
 const submit=(ts:number)=>{if(!raw.trim()||done||feedback)return;const a=finalizeAttempt(item,raw,{presentedAt:presentedAt.current||ts,firstInputAt:firstInputAt.current,submittedAt:ts,edits,backspaces});const all=[...attempts,a];setAttempts(all);const needsRepair=mode==='adaptive'&&(!a.correct||a.reason==='strategy_missed'||a.reason==='slow_recall');if(needsRepair&&repairs<6){const repair={...generateArithmeticSet(grade,1,sessionSeed.current+1000+idx,[item.skillId])[0],expectedMs:item.expectedMs};setItems(xs=>{if(!xs)return xs;const copy=[...xs];const at=Math.min(copy.length,idx+3);copy.splice(at,0,repair);return copy});setRepairs(x=>x+1)}if(mode==='adaptive'&&(!a.correct||a.reason!=='correct'))setFeedback(a);else advance(all,ts)};
 if(done){const last=attempts;const correct=last.filter(a=>a.correct).length;const med=[...last.map(a=>a.firstInputMs)].sort((a,b)=>a-b)[Math.floor(last.length/2)]||0;const reasons=Object.entries(last.reduce((m,a)=>{if(!a.correct||a.reason!=="correct")m[a.reason]=(m[a.reason]||0)+1;return m},{ } as Record<string,number>)).sort((a,b)=>b[1]-a[1]);return <div className="report-shell arithmetic-result"><section className="score-hero"><div><span className="eyebrow">{profile.titleZh} · PERSONAL DIAGNOSIS</span><h1>{mode==='diagnostic'?'诊断完成':'训练完成'}</h1><p>{saving?'正在保存学习数据…':'本次行为数据已写入个人模型'}</p></div><div className="score-ring"><strong>{correct}</strong><span>/ {last.length}</span><small>{Math.round(correct/last.length*100)}%</small></div></section><section className="result-stats"><article><strong>{(med/1000).toFixed(1)}s</strong><span>中位启动</span></article><article><strong>{last.filter(a=>a.reason==='impulsive').length}</strong><span>冲动型错误</span></article><article><strong>{last.filter(a=>a.reason==='strategy_missed'||a.reason==='slow_recall').length}</strong><span>效率问题</span></article></section><section className="arithmetic-dashboard-grid"><article className="report-card"><h2>错因与习惯</h2>{reasons.length?reasons.slice(0,6).map(([r,c])=><div className="diagnosis-row" key={r}><span>{REASON_ZH[r as ErrorReason]||r}</span><strong>{c}题</strong></div>):<p>本轮没有明显错误模式。</p>}</article><article className="report-card"><h2>下一轮怎么练</h2>{done.summaryZh.map((x,i)=><p key={i}>{x}</p>)}{done.accuracyFocusSkills.length>0&&<><h3>准确性复核</h3><div className="focus-chips">{done.accuracyFocusSkills.map(id=><span key={id}>{profile.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></>}{done.monitorSkills.length>0&&<><h3>观察 / 复测</h3><div className="focus-chips">{done.monitorSkills.map(id=><span key={id}>{profile.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></>}{done.fluencyFocusSkills.length>0&&<><h3>提速 / 巧算</h3><div className="focus-chips">{done.fluencyFocusSkills.map(id=><span key={id}>{profile.skills.find(s=>s.id===id)?.labelZh||id}</span>)}</div></>}</article></section><div className="report-actions"><Link className="primary-button" href={`/arithmetic/session/${grade}?mode=adaptive&student=${encodeURIComponent(studentId)}`}>立即开始个性化下一轮</Link><Link className="secondary-button" href="/arithmetic">返回口算中心</Link></div></div>}
 return <div className="mental-shell"><section className="mental-topbar"><div><span className="eyebrow">{profile.titleZh}</span><strong>{mode==='diagnostic'?'20题基线诊断':mode==='speed'?'速度挑战':'个性化智能训练'}</strong></div><div className="mental-progress"><span>{idx+1}</span> / {items.length}<i><b style={{width:`${(idx/items.length)*100}%`}}/></i></div><Link className="ghost-button" href="/arithmetic">退出</Link></section><section className="mental-card"><div className="mental-meta"><span>{mode==='diagnostic'?'基线诊断 · 不提示策略':profile.skills.find(s=>s.id===item.skillId)?.labelZh}</span>{mode!=='diagnostic'&&<small>目标 ≤ {(item.expectedMs/1000).toFixed(1)}s</small>}</div><div className="mental-prompt">{item.prompt}</div><form className="mental-answer-form" onSubmit={e=>{e.preventDefault();submit(e.timeStamp)}}><input ref={inputRef} className="mental-input" inputMode="decimal" autoComplete="off" readOnly={touch} value={raw} onKeyDown={e=>{if(e.key==='Backspace')setBackspaces(x=>x+1);if(e.key==='Enter'){e.preventDefault();submit(e.timeStamp)}}} onChange={e=>{const next=e.target.value;if(firstInputAt.current===null&&next!=="")firstInputAt.current=e.timeStamp;const normalAppend=next.length===raw.length+1&&next.startsWith(raw);const deletion=next.length<raw.length;if(raw!==""&&next!==raw&&!normalAppend&&!deletion)setEdits(x=>x+1);setRaw(next)}} placeholder={touch?"用下方数字键盘":"输入答案，按 Enter"}/><button className="mental-hidden-submit" type="submit" tabIndex={-1} aria-hidden="true">提交</button></form><div className="mental-keypad">{["1","2","3","4","5","6","7","8","9"].map(k=><button type="button" key={k} onClick={e=>pushChar(k,e.timeStamp)}>{k}</button>)}<button type="button" className="key-back" onClick={erase}>⌫</button><button type="button" onClick={e=>pushChar("0",e.timeStamp)}>0</button><button type="button" onClick={e=>pushChar(".",e.timeStamp)}>.</button><button type="button" className="key-enter" disabled={!raw.trim()} onClick={e=>submit(e.timeStamp)}>↵</button></div>{feedback&&<div className={`mental-feedback ${feedback.correct?'ok':'bad'}`}><strong>{feedback.correct?'✓ 答对了':`✕ 正确答案：${feedback.item.answer}`}</strong><p>{REASON_ZH[feedback.reason]} · {STRATEGY_GUIDE[feedback.item.strategy].zh}</p><button autoFocus className="secondary-button" onClick={e=>advance(attempts,e.timeStamp)}>按 Enter 继续</button></div>}<div className="mental-hint">{touch?"直接用数字键盘作答，↵提交。":"直接输入答案，按 Enter 提交，全程无需鼠标。"} 系统分别记录思考启动、输入执行和总耗时。</div></section></div>;
}
