"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { CLEVER_NODE_GUIDE,GRADE_PROFILES,STRATEGY_GUIDE,type ArithmeticGrade } from "@/lib/arithmetic";
import { ARITHMETIC_GRADE_GUIDE } from "@/lib/arithmetic-grade-guide";
import { K12_GRADE_BANDS,K12_GRADE_CROSSWALK,K12_GRADE_NOTE,K12_GRADE_NOTE_EN } from "@/lib/k12-grade-system";
import { buildTrainingPlan,type ArithmeticSession } from "@/lib/arithmetic-analytics";
import { buildLearnerProfile,type LearnerSignal } from "@/lib/math-engine";
import { useSiteLanguage } from "@/lib/site-language";
import styles from "./ArithmeticDashboard.module.css";

const stageIdForGrade=(grade:ArithmeticGrade)=>grade<=5?"primary":grade<=8?"lower-secondary":"upper-secondary";
const compactGradeLabel=(grade:ArithmeticGrade)=>`G${grade}`;

const UI={
 zh:{
  heroEye:"智能计算训练",heroTitle1:"计算诊断",heroTitle2:"与智能训练",heroCopy:"不是单纯刷题。系统同时分析正确率、启动速度、总耗时、修改/退格行为、错误类型和计算结构识别，用下一轮最小必要题量修复最值得修复的问题。",
  modeEye:"训练模式中心",startNow:"现在开始练",current:"当前",stageAria:"选择 K-12 学段",gradeAria:"选择年级",gradeWord:"年级",content:"训练内容",how:"怎么练",watch:"重点观察",benchmark:"达标参考",benchmarkCopy:"方法稳定",
  ai:"AI 推荐",adaptive:"智能训练",adaptiveCopy:"根据你的最近表现，自动挑选最值得练的题和最小必要题量。",adaptiveStart:"开始智能训练",
  method:"学方法",guided:"跟我算",guidedPrimary:"分层提示、逐步撤掉支架，把“老师带着会”练成自己独立会。",guidedSecondary:"卡住时只给一步关键提示，定位符号、公式、变形或运算顺序问题。",guidedStart:"开始引导训练",
  observe:"练眼力",discover:"先别算",discoverCopy:"先观察结构、比较变形，再决定怎么计算，训练真正的数感与策略选择。",discoverStart:"开始结构发现",
  weak:"找薄弱点",diagnostic:"专项诊断",diagnosticCopy:"按当前年级核心模块均衡抽题，先建立每个技能的可靠基线。",diagnosticStart:"开始专项诊断",
  diagShort:"诊断",rediagnose:"重新诊断",baseline:"20题基线诊断",updateBaseline:"更新能力基线",speedShort:"速度",timedShort:"限时",speed:"极速练",timed:"限时计算",speedCopy:"提高自动化与反应速度",timedCopy:"提升准确率、步骤熟练度与计算节奏",paper:"纸笔",a4:"A4 计算",paperCopy:"批量生成打印练习",
  student:"学生画像",studentCopy:"正式模拟、计算速度、错因与训练历史统一进入同一个个人学习档案。",fullReport:"查看完整学习报告",
  cognition:"数学认知画像 · 新引擎",evidenceTitle:"结构与策略行为证据",evidenceCopy:"这里只展示已经被行为数据观测到的能力，不根据单次答题猜测“天赋”或“理解力”。",evidence:"条证据",confidence:"置信",
  gradeStandard:"这个年级要练到什么程度",targetAccuracy:"目标正确率",targetMedian:"目标中位用时",completed:"已完成训练",target:"目标",
  personal:"个性化模型",personalNow:"当前个人训练建议",personalFirst:"先建立个人基线",personalEmpty:"第一次先做20题诊断。系统会建立每个技能的“准确性 × 流畅度 × 稳定性 × 策略效率”基线，再决定下一轮训练内容。",
  profile:"能力画像",fourD:"四维技能画像",fourDCopy:"把每个技能拆成准确性、流畅度、稳定性和策略效率。灰色表示证据不足，不强行下结论。",stable:"稳定",attention:"需关注",insufficient:"证据不足",questions:"题",evidenceWord:"证据",noSample:"尚无样本",start:"启动",next:"下一步",speedMet:"达到年级速度参考",
  structure:"结构能力",tree:"巧算能力树",treeCopy:"颜色直接表示当前状态；证据条越长，结论越可靠。系统下一轮优先处理橙色节点。",nextPriority:"下一轮优先",accuracy:"正确率",retest:"复测",accuracyFix:"补准确",speedFix:"提速度",fewSamples:"样本少",awaitSample:"待采样",
  probe:"诊断探针",whereSlow:"慢在哪里？",probeCopy:"用相似题对照，区分“基础算力慢”和“没有及时发现结构”。",pairs:"组对照",normal:"普通",efficientCalc:"巧算",structureGap:"结构识别缺口",generalSlow:"基础流畅度偏慢",monitor:"继续观察",structureNormal:"策略识别正常",notEnough:"样本不足",
  strategy:"策略画像",habit:"哪些方法已经变成习惯？",habitCopy:"不再堆文字：直接看正确率、启动速度和证据量。",
 },
 en:{
  heroEye:"ADAPTIVE CALCULATION",heroTitle1:"Calculation diagnosis",heroTitle2:"and adaptive training",heroCopy:"This is not repetitive drilling. The system tracks accuracy, response start, total time, edits, error patterns and structural strategy use, then assigns the smallest useful next set.",
  modeEye:"TRAINING MODES",startNow:"Start training",current:"Current",stageAria:"Choose K-12 stage",gradeAria:"Choose grade",gradeWord:"Grade",content:"Training focus",how:"How to train",watch:"What to watch",benchmark:"Benchmark",benchmarkCopy:"with stable methods",
  ai:"AI recommended",adaptive:"Adaptive training",adaptiveCopy:"Uses recent performance to select the highest-value skills and the minimum useful number of questions.",adaptiveStart:"Start adaptive training",
  method:"Learn the method",guided:"Guided calculation",guidedPrimary:"Use concise scaffolding, then remove it step by step until the student can solve independently.",guidedSecondary:"When stuck, show only the next key step to locate sign, formula, transformation or order-of-operations issues.",guidedStart:"Start guided training",
  observe:"See the structure",discover:"Look before calculating",discoverCopy:"Inspect structure and equivalent forms before choosing a method. This builds number sense and strategy selection.",discoverStart:"Start structure discovery",
  weak:"Find weak points",diagnostic:"Skill diagnostic",diagnosticCopy:"Sample the core modules for this grade evenly to establish a reliable baseline for each skill.",diagnosticStart:"Start diagnostic",
  diagShort:"Diagnostic",rediagnose:"Run diagnostic again",baseline:"20-question baseline",updateBaseline:"Refresh skill baseline",speedShort:"Speed",timedShort:"Timed",speed:"Fluency sprint",timed:"Timed calculation",speedCopy:"Improve automaticity and response speed",timedCopy:"Improve accuracy, procedural fluency and calculation pace",paper:"Paper",a4:"A4 practice",paperCopy:"Generate printable calculation practice",
  student:"Learner profile",studentCopy:"Mock exams, calculation speed, error causes and training history feed one learner record.",fullReport:"View full learning report",
  cognition:"MATHEMATICAL LEARNER MODEL",evidenceTitle:"Structural and strategy evidence",evidenceCopy:"Only abilities supported by observed behavior are shown; the system does not infer talent or understanding from a single response.",evidence:"evidence items",confidence:"Confidence",
  gradeStandard:"What mastery looks like at this grade",targetAccuracy:"Target accuracy",targetMedian:"Target median time",completed:"Sessions completed",target:"Target",
  personal:"Personalized model",personalNow:"Current training recommendation",personalFirst:"Build a personal baseline",personalEmpty:"Start with a 20-question diagnostic. The system builds a baseline for accuracy, fluency, stability and strategy efficiency before choosing the next training set.",
  profile:"Skill profile",fourD:"Four-dimensional skill profile",fourDCopy:"Each skill is separated into accuracy, fluency, stability and strategy efficiency. Gray means evidence is still insufficient.",stable:"Stable",attention:"Needs attention",insufficient:"Insufficient evidence",questions:"questions",evidenceWord:"Evidence",noSample:"No sample yet",start:"Start",next:"Next",speedMet:"Meets the grade speed reference",
  structure:"Structural fluency",tree:"Efficient-calculation tree",treeCopy:"Color shows current status and the evidence bar shows confidence. The next round prioritizes orange nodes.",nextPriority:"Next priority",accuracy:"Accuracy",retest:"Retest",accuracyFix:"Fix accuracy",speedFix:"Build fluency",fewSamples:"Low evidence",awaitSample:"Awaiting samples",
  probe:"Diagnostic probe",whereSlow:"Where is the slowdown?",probeCopy:"Matched problems separate general calculation slowness from delayed structure recognition.",pairs:"matched pairs",normal:"Standard",efficientCalc:"Efficient",structureGap:"Structure-recognition gap",generalSlow:"General fluency is slow",monitor:"Keep monitoring",structureNormal:"Strategy recognition looks efficient",notEnough:"Insufficient evidence",
  strategy:"Strategy profile",habit:"Which methods are becoming habits?",habitCopy:"Use accuracy, response start and evidence volume instead of another wall of text.",
 },
} as const;

export default function ArithmeticDashboard({user}:{user:{id:string;name:string;candidateNo:string;grade:number}}){
 const lang=useSiteLanguage(),ui=UI[lang];
 const [sessions,setSessions]=useState<ArithmeticSession[]>([]);
 const [signals,setSignals]=useState<LearnerSignal[]>([]);
 const [selected,setSelected]=useState<ArithmeticGrade>(Math.min(12,Math.max(1,user.grade)) as ArithmeticGrade);
 const isGuest=user.candidateNo==="GUEST";
 useEffect(()=>{fetch(`/api/arithmetic/sessions`).then(r=>r.json()).then(x=>setSessions(x.sessions||[])).catch(()=>setSessions([]));},[]);
 useEffect(()=>{fetch(`/api/math-engine/signals?grade=${selected}`).then(r=>r.json()).then(x=>setSignals(x.signals||[])).catch(()=>setSignals([]));},[selected]);

 const p=GRADE_PROFILES[selected],guide=ARITHMETIC_GRADE_GUIDE[selected],crosswalk=K12_GRADE_CROSSWALK[selected],plan=buildTrainingPlan(selected,sessions),mathProfile=buildLearnerProfile(signals);
 const gradeSessions=sessions.filter(s=>s.grade===selected),attempts=gradeSessions.flatMap(s=>s.attempts),accuracy=attempts.length?attempts.filter(a=>a.correct).length/attempts.length:0;
 const currentStage=stageIdForGrade(selected),stage=K12_GRADE_BANDS.find(s=>s.id===currentStage)!;
 const gradeTitle=lang==="zh"?p.titleZh:p.titleEn;
 const strategyCount=new Set(p.skills.flatMap(s=>s.strategies)).size;
 const skillLabel=(id:string)=>{const skill=p.skills.find(s=>s.id===id);return lang==="zh"?(skill?.labelZh||id):(skill?.labelEn||id)};
 const guideCopy=lang==="zh"?{headline:guide.headline,goal:guide.goal,training:guide.training,watch:guide.watch}:{headline:guide.headlineEn,goal:guide.goalEn,training:guide.trainingEn,watch:guide.watchEn};
 const cognitiveRows=lang==="zh"?[
  {label:"结构/策略",value:mathProfile.strategyEvidence.score,note:"是否主动利用结构"},
  {label:"独立完成",value:mathProfile.independence.score,note:"是否减少提示依赖"},
  {label:"提示依赖",value:mathProfile.hintReliance.score,note:"越低越独立"},
  {label:"自动化",value:mathProfile.fluency.score,note:"正确且快速稳定"},
 ]:[
  {label:"Structure / strategy",value:mathProfile.strategyEvidence.score,note:"Uses mathematical structure proactively"},
  {label:"Independence",value:mathProfile.independence.score,note:"Completes more work without hints"},
  {label:"Hint reliance",value:mathProfile.hintReliance.score,note:"Lower means more independent"},
  {label:"Fluency",value:mathProfile.fluency.score,note:"Accurate, fast and stable"},
 ];
 const dimensionLabels=lang==="zh"?["准","快","稳","巧"]:["Acc","Flu","Stab","Strat"];
 const nodeStatusLabel=(status:string)=>status==="mastered"?ui.stable:status==="needs_accuracy"?ui.accuracyFix:status==="needs_fluency"?ui.speedFix:status==="monitor"?ui.retest:ui.fewSamples;
 const probeStatusLabel=(status:string)=>status==="strategy_gap"?ui.structureGap:status==="general_slow"?ui.generalSlow:status==="monitor"?ui.monitor:status==="efficient"?ui.structureNormal:ui.notEnough;
 const evidencedMetrics=plan.metrics.filter(m=>m.attempts>=4);
 const avg=(values:(number|null)[])=>{const xs=values.filter((v):v is number=>v!==null);return xs.length?Math.round(xs.reduce((a,b)=>a+b,0)/xs.length):0};
 const abilityScores=[
  {key:"accuracy",label:lang==="zh"?"准确":"Accuracy",value:avg(evidencedMetrics.map(m=>m.accuracyScore))},
  {key:"fluency",label:lang==="zh"?"速度":"Speed",value:avg(evidencedMetrics.map(m=>m.fluencyScore))},
  {key:"stability",label:lang==="zh"?"稳定":"Stability",value:avg(evidencedMetrics.map(m=>m.stabilityScore))},
  {key:"strategy",label:lang==="zh"?"策略":"Strategy",value:avg(evidencedMetrics.map(m=>m.strategyScore))},
 ];
 const radarPoint=(index:number,value:number)=>{const a=(-90+index*90)*Math.PI/180,r=70*Math.max(0,Math.min(100,value))/100;return `${100+Math.cos(a)*r},${100+Math.sin(a)*r}`};
 const radarPoints=abilityScores.map((x,i)=>radarPoint(i,x.value)).join(" ");
 const ranked=[...evidencedMetrics].sort((a,b)=>{const sa=avg([a.accuracyScore,a.fluencyScore,a.stabilityScore,a.strategyScore]),sb=avg([b.accuracyScore,b.fluencyScore,b.stabilityScore,b.strategyScore]);return sb-sa});
 const strongest=ranked[0],weakest=[...evidencedMetrics].sort((a,b)=>b.priority-a.priority)[0];
 const reasonLabel=(code:string)=>{const zh:Record<string,string>={slow_recall:"基础事实提取偏慢",impulsive:"作答过快，容易冲动出错",hesitation:"犹豫和反复修改较多",near_miss:"接近答案但精度不足",operation_confusion:"运算关系容易混淆",place_value:"数位理解需要加强",fact_gap:"基础算式记忆不牢",strategy_missed:"没有及时识别更优计算结构",unknown:"需要更多样本定位原因"};const en:Record<string,string>={slow_recall:"Basic fact recall is slow",impulsive:"Responses are too impulsive",hesitation:"Frequent hesitation or edits",near_miss:"Near-miss accuracy errors",operation_confusion:"Operation relationships are confused",place_value:"Place-value understanding needs work",fact_gap:"Basic facts are not yet automatic",strategy_missed:"Efficient structure is often missed",unknown:"More evidence is needed"};return (lang==="zh"?zh:en)[code]||code};
 const topReason=plan.reasons[0];

 return <div className="home-shell arithmetic-home">
  <section className="hero-card arithmetic-hero"><div className="eyebrow">{ui.heroEye}</div><h1>{ui.heroTitle1}<br/><span>{ui.heroTitle2}</span></h1><p className="hero-copy">{ui.heroCopy}</p><div className="hero-actions arithmetic-hero-actions"><Link className="primary-button" href={`/arithmetic/session/${selected}?mode=diagnostic`}>{lang==="zh"?"无需登录 · 立即做 20 题诊断":"No sign-in · Start 20-question diagnostic"}</Link><Link className="secondary-button" href="#training-launchpad">{lang==="zh"?"先选年级":"Choose grade first"}</Link></div>{isGuest&&<p className="guest-access-note">{lang==="zh"?"游客可直接练习并查看基础成绩；登录只用于长期记录和跨设备同步。":"Guests can practice and view basic results immediately. Sign in only for long-term history and sync."}</p>}</section>

  <section className="training-launchpad" id="training-launchpad">
   <div className="training-launchpad-head"><div><span className="eyebrow">{ui.modeEye}</span><h2>{ui.startNow}</h2><p>{ui.current} {crosswalk.international} · {gradeTitle}</p></div><div className={styles.gradePicker}><div className={styles.stageSwitcher} aria-label={ui.stageAria}>{K12_GRADE_BANDS.map(s=><button key={s.id} type="button" className={currentStage===s.id?styles.active:""} onClick={()=>{if(currentStage!==s.id)setSelected(s.grades[0])}}><strong>{lang==="zh"?s.zh:s.label}</strong><small>{lang==="zh"?`${s.label} · ${s.range}`:s.range}</small></button>)}</div><div className={styles.gradeSwitcher} aria-label={ui.gradeAria}>{stage.grades.map(g=><button key={g} type="button" className={selected===g?styles.active:""} onClick={()=>setSelected(g)}>{compactGradeLabel(g)}<small>{ui.gradeWord}</small></button>)}</div></div></div>
   <div className={styles.gradeCrosswalk}><div><b>International</b><span>{crosswalk.international}</span></div><div><b>US</b><span>{crosswalk.us}</span></div><div><b>England</b><span>{crosswalk.england}</span></div><div><b>Australia</b><span>{crosswalk.australia}</span></div><div><b>IB</b><span>{crosswalk.ib}</span></div><small>{lang==="zh"?K12_GRADE_NOTE:K12_GRADE_NOTE_EN}</small></div>
   <div className={styles.gradeGuide}><div className={styles.gradeGuideIntro}><span>{crosswalk.international} · {gradeTitle} · {ui.content}</span><h3>{guideCopy.headline}</h3><p>{guideCopy.goal}</p><div className={styles.curriculumCount}><b>{p.skills.length}</b><span>{lang==="zh"?"个核心模块":"core modules"}</span><i>+</i><b>{strategyCount}</b><span>{lang==="zh"?"种关键方法":"key methods"}</span></div></div><div className={styles.guideSkills}>{p.skills.map((skill,i)=><article key={skill.id}><div><span>{String(i+1).padStart(2,"0")}</span><b>{lang==="zh"?skill.labelZh:skill.labelEn}</b></div><div className={styles.strategyChips}>{skill.strategies.map(strategy=><em key={strategy}>{STRATEGY_GUIDE[strategy][lang]}</em>)}</div><small>{lang==="zh"?`典型题目标约 ≤ ${(skill.targetMs/1000).toFixed(1)} 秒`:`Typical target ≤ ${(skill.targetMs/1000).toFixed(1)}s`}</small></article>)}</div><div className={styles.guideMeta}><div><b>{ui.how}</b><span>{guideCopy.training}</span></div><div><b>{ui.watch}</b><span>{guideCopy.watch}</span></div><div><b>{ui.benchmark}</b><span>{lang==="zh"?`正确率 ≥ ${Math.round(p.targetAccuracy*100)}% · 典型题中位用时约 ≤ ${(p.targetMedianMs/1000).toFixed(1)} 秒 · ${ui.benchmarkCopy}。`:`Accuracy ≥ ${Math.round(p.targetAccuracy*100)}% · typical median time ≤ ${(p.targetMedianMs/1000).toFixed(1)}s · ${ui.benchmarkCopy}.`}</span></div></div></div>
   <div className="training-primary-grid">
    <Link className="training-mode-card training-mode-card--adaptive" href={`/arithmetic/session/${selected}?mode=adaptive`}><div className="training-mode-top"><span className="training-mode-number">01</span><em>{ui.ai}</em></div><h3>{ui.adaptive}</h3><p>{ui.adaptiveCopy}</p><strong>{ui.adaptiveStart} <span>→</span></strong></Link>
    <Link className="training-mode-card training-mode-card--guided" href={`/arithmetic/session/${selected}?mode=guided`}><div className="training-mode-top"><span className="training-mode-number">02</span><em>{ui.method}</em></div><h3>{ui.guided}</h3><p>{selected<=6?ui.guidedPrimary:ui.guidedSecondary}</p><strong>{ui.guidedStart} <span>→</span></strong></Link>
    {selected<=6?<Link className="training-mode-card training-mode-card--discovery" href={`/arithmetic/discovery/${selected}`}><div className="training-mode-top"><span className="training-mode-number">03</span><em>{ui.observe}</em></div><h3>{ui.discover}</h3><p>{ui.discoverCopy}</p><strong>{ui.discoverStart} <span>→</span></strong></Link>:<Link className="training-mode-card training-mode-card--discovery" href={`/arithmetic/session/${selected}?mode=diagnostic`}><div className="training-mode-top"><span className="training-mode-number">03</span><em>{ui.weak}</em></div><h3>{ui.diagnostic}</h3><p>{ui.diagnosticCopy}</p><strong>{ui.diagnosticStart} <span>→</span></strong></Link>}
   </div>
   <div className="training-tool-row"><Link href={`/arithmetic/session/${selected}?mode=diagnostic`}><span>{ui.diagShort}</span><b>{attempts.length?ui.rediagnose:ui.baseline}</b><small>{ui.updateBaseline}</small></Link><Link href={`/arithmetic/session/${selected}?mode=speed`}><span>{selected<=6?ui.speedShort:ui.timedShort}</span><b>{selected<=6?ui.speed:ui.timed}</b><small>{selected<=6?ui.speedCopy:ui.timedCopy}</small></Link><Link href={`/arithmetic/print?grade=${selected}`}><span>{ui.paper}</span><b>{ui.a4}</b><small>{ui.paperCopy}</small></Link></div>
  </section>

  <section className="student-profile-strip"><div><span className="eyebrow">{ui.student}</span><h2>{isGuest?(lang==="zh"?"正在游客体验":"Guest session"):`${user.name} · ${user.candidateNo}`}</h2><p>{isGuest?(lang==="zh"?"不用注册也可以完成训练并查看本次成绩。需要长期保存时再登录即可。":"Complete practice and see this result without an account. Sign in only when you want long-term history."):ui.studentCopy}</p></div><Link className="secondary-button" href={isGuest?"/login?next=/arithmetic":"/student"}>{isGuest?(lang==="zh"?"登录后保存长期记录":"Sign in for long-term history"):ui.fullReport}</Link></section>

  {attempts.length>0&&<section className="parent-diagnosis-card">
   <div className="parent-diagnosis-summary">
    <span className="eyebrow">{lang==="zh"?"当前诊断":"CURRENT DIAGNOSIS"}</span>
    <h2>{lang==="zh"?"先看结论：孩子现在强在哪、卡在哪":"The short answer: strengths, gaps and what to do next"}</h2>
    <div className="diagnosis-cards">
     <article className="diagnosis-good"><span>{lang==="zh"?"强项":"Strength"}</span><b>{strongest?skillLabel(strongest.skillId):(lang==="zh"?"样本仍在积累":"Building evidence")}</b><p>{strongest? (lang==="zh"?`目前证据中，这一项整体表现最稳定。`:`This is currently the most stable evidenced skill.`):(lang==="zh"?"再完成一些题目后会自动识别。":"More practice will identify this automatically.")}</p></article>
     <article className="diagnosis-watch"><span>{lang==="zh"?"最该先补":"Priority gap"}</span><b>{weakest?skillLabel(weakest.skillId):(lang==="zh"?"需要更多样本":"More evidence needed")}</b><p>{weakest?(weakest.status==="needs_accuracy"?(lang==="zh"?"先补正确率，不急着提速。":"Fix accuracy before pushing speed."):(weakest.status==="needs_fluency"?(lang==="zh"?"正确率基本够，下一步重点提速度和自动化。":"Accuracy is adequate; build speed and automaticity next."):(lang==="zh"?"继续补样本并针对性复测。":"Collect more evidence with targeted retesting."))):(lang==="zh"?"完成诊断后给出。":"Available after diagnostic.")}</p></article>
     <article><span>{lang==="zh"?"可能原因":"Likely cause"}</span><b>{topReason?reasonLabel(topReason.code):(lang==="zh"?"暂无稳定错因":"No stable error pattern yet")}</b><p>{topReason?(lang==="zh"?`最近记录到 ${topReason.count} 次相关行为。`:`${topReason.count} related events observed recently.`):(lang==="zh"?"系统不会在证据不足时猜原因。":"The system will not guess without evidence.")}</p></article>
     <article className="diagnosis-next"><span>{lang==="zh"?"现在就做":"Do next"}</span><b>{plan.focusSkills.length?skillLabel(plan.focusSkills[0]):(lang==="zh"?"继续智能训练":"Continue adaptive practice")}</b><p>{lang==="zh"?"系统按当前证据自动缩小下一组题量，优先修最值得修的问题。":"The next set is kept small and focused on the highest-value gap."}</p><Link href={`/arithmetic/session/${selected}?mode=adaptive`}>{lang==="zh"?"开始这组训练 →":"Start this set →"}</Link></article>
    </div>
   </div>
   {evidencedMetrics.length>0&&<div className="ability-radar-wrap"><div className="ability-radar"><svg viewBox="0 0 200 200" role="img" aria-label={lang==="zh"?"四维能力图":"Four-dimension ability map"}><polygon className="radar-grid outer" points="100,30 170,100 100,170 30,100"/><polygon className="radar-grid inner" points="100,65 135,100 100,135 65,100"/><line x1="100" y1="30" x2="100" y2="170"/><line x1="30" y1="100" x2="170" y2="100"/><polygon className="radar-value" points={radarPoints}/><circle cx={radarPoint(0,abilityScores[0].value).split(",")[0]} cy={radarPoint(0,abilityScores[0].value).split(",")[1]} r="3"/><circle cx={radarPoint(1,abilityScores[1].value).split(",")[0]} cy={radarPoint(1,abilityScores[1].value).split(",")[1]} r="3"/><circle cx={radarPoint(2,abilityScores[2].value).split(",")[0]} cy={radarPoint(2,abilityScores[2].value).split(",")[1]} r="3"/><circle cx={radarPoint(3,abilityScores[3].value).split(",")[0]} cy={radarPoint(3,abilityScores[3].value).split(",")[1]} r="3"/></svg>{abilityScores.map((x,i)=><div className={`radar-label radar-label-${i}`} key={x.key}><b>{x.label}</b><span>{x.value}</span></div>)}</div><p>{lang==="zh"?"图形越向外，当前证据越强；它只使用已有训练数据。":"Farther outward means stronger current evidence; only observed practice data is used."}</p></div>}
  </section>}

  {attempts.length===0?<section className="diagnostic-empty-state"><div className="diagnostic-empty-icon" aria-hidden="true">?</div><div><span className="eyebrow">{lang==="zh"?"先诊断，再训练":"DIAGNOSE FIRST"}</span><h2>{lang==="zh"?"还没有足够数据判断孩子的强弱":"Not enough evidence yet to judge strengths and weaknesses"}</h2><p>{lang==="zh"?"现在显示分数没有意义。先完成一次 20 题基线诊断，系统才会根据正确率、速度、稳定性和策略使用情况告诉你：哪里强、哪里弱、为什么，以及下一步最值得练什么。":"Showing scores now would be misleading. Complete the 20-question baseline first; then the system can explain strengths, weaknesses, likely causes and the highest-value next practice."}</p><div className="diagnostic-deliverables"><span>{lang==="zh"?"✓ 强项与薄弱点":"✓ Strengths & gaps"}</span><span>{lang==="zh"?"✓ 错误原因":"✓ Error causes"}</span><span>{lang==="zh"?"✓ 下一步训练处方":"✓ Next practice plan"}</span></div></div><Link className="primary-button" href={`/arithmetic/session/${selected}?mode=diagnostic`}>{lang==="zh"?"开始 20 题诊断":"Start 20-question diagnostic"}</Link></section>:<section className="report-card cognitive-profile-card" style={{marginTop:18}}><div className="cognitive-profile-head"><div><span className="eyebrow">{ui.cognition}</span><h2>{ui.evidenceTitle}</h2><p>{ui.evidenceCopy}</p></div><div className="evidence-badge"><strong>{signals.length}</strong><span>{ui.evidence}</span><small>{ui.confidence} {mathProfile.strategyEvidence.evidence}%</small></div></div><div className="cognitive-bars">{cognitiveRows.map(({label,value,note})=><div className="cognitive-bar-row" key={label}><div><b>{label}</b><small>{note}</small></div><div className="cognitive-bar-track"><i style={{width:value===null?"0%":`${value}%`}}/></div><strong>{value===null?"—":`${value}%`}</strong></div>)}</div></section>}

  <section className="arithmetic-dashboard-grid"><article className="report-card"><span className="eyebrow">{gradeTitle}</span><h2>{ui.gradeStandard}</h2><div className="target-strip"><div><strong>{Math.round(p.targetAccuracy*100)}%</strong><span>{ui.targetAccuracy}</span></div><div><strong>{(p.targetMedianMs/1000).toFixed(1)}s</strong><span>{ui.targetMedian}</span></div><div><strong>{gradeSessions.length}</strong><span>{ui.completed}</span></div></div><div className="skill-list">{p.skills.map(s=><div key={s.id}><b>{lang==="zh"?s.labelZh:s.labelEn}</b><span>{ui.target} {(s.targetMs/1000).toFixed(1)}s · {s.strategies.map(strategy=>STRATEGY_GUIDE[strategy][lang]).join(" · ")}</span></div>)}</div></article>
   <article className="report-card"><span className="eyebrow">{ui.personal}</span><h2>{attempts.length?ui.personalNow:ui.personalFirst}</h2>{attempts.length?<><p className="big-accuracy">{(accuracy*100).toFixed(0)}%</p>{lang==="zh"?plan.summaryZh.map((x,i)=><p key={i}>{x}</p>):<p>Based on recent evidence, prioritize the skills below while maintaining accuracy and stable methods.</p>}<div className="focus-chips">{plan.focusSkills.map(id=><span key={id}>{skillLabel(id)}</span>)}</div></>:<p>{ui.personalEmpty}</p>}</article></section>

  {attempts.length>0&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">{ui.profile}</span><h2>{ui.fourD}</h2><p>{ui.fourDCopy}</p></div><div className="analysis-legend"><span><i className="good"/>{ui.stable}</span><span><i className="watch"/>{ui.attention}</span><span><i/>{ui.insufficient}</span></div></div><div className="skill-visual-list">{plan.metrics.map(m=>{const skill=p.skills.find(x=>x.id===m.skillId);const scores=[[dimensionLabels[0],m.accuracyScore],[dimensionLabels[1],m.fluencyScore],[dimensionLabels[2],m.stabilityScore],[dimensionLabels[3],m.strategyScore]] as const;return <article className="skill-visual-row" key={m.skillId}><div className="skill-visual-label"><b>{skillLabel(m.skillId)}</b><span>{m.attempts} {ui.questions} · {ui.evidenceWord} {m.evidence}%</span><small>{m.attempts===0?ui.noSample:m.medianMs>(skill?.targetMs||0)?`${ui.start} ${(m.medianMs/1000).toFixed(1)}s · ${ui.next} ≤ ${(m.personalTargetMs/1000).toFixed(1)}s`:`${ui.start} ${(m.medianMs/1000).toFixed(1)}s · ${ui.speedMet}`}</small></div><div className="skill-score-grid">{scores.map(([label,value])=><div className={`skill-score ${value===null?"empty":value>=85?"good":value<70?"watch":""}`} key={label}><span>{label}</span><div><i style={{width:value===null?"0%":`${value}%`}}/></div><strong>{value===null?"—":value}</strong></div>)}</div></article>})}</div></section>}

  {attempts.length>0&&selected<=6&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">{ui.structure}</span><h2>{ui.tree}</h2><p>{ui.treeCopy}</p></div>{plan.focusNodes.length>0&&<div className="focus-summary"><small>{ui.nextPriority}</small><strong>{plan.focusNodes.map(x=>CLEVER_NODE_GUIDE[x][lang]).join(" · ")}</strong></div>}</div><div className="ability-node-grid">{plan.nodeMetrics.map(m=>{const status=m.status==="mastered"?"good":m.status==="needs_accuracy"||m.status==="needs_fluency"?"watch":m.status==="monitor"?"monitor":"empty";return <article className={`ability-node ${status}`} key={m.node}><header><b>{CLEVER_NODE_GUIDE[m.node][lang]}</b><span>{nodeStatusLabel(m.status)}</span></header><div className="ability-node-main"><strong>{m.attempts?Math.round(m.correct/m.attempts*100):0}%</strong><small>{ui.accuracy}</small><em>{m.attempts} {ui.questions}</em></div><div className="evidence-track"><i style={{width:`${m.evidence}%`}}/></div><footer><span>{ui.evidenceWord} {m.evidence}%</span><span>{m.attempts?`${ui.start} ${(m.medianMs/1000).toFixed(1)}s`:ui.awaitSample}</span></footer></article>})}</div></section>}

  {attempts.length>0&&selected<=6&&plan.probeMetrics.length>0&&<section className="analysis-section compact-analysis"><div className="analysis-section-head"><div><span className="eyebrow">{ui.probe}</span><h2>{ui.whereSlow}</h2><p>{ui.probeCopy}</p></div></div><div className="probe-list">{plan.probeMetrics.map(m=><article key={m.node}><div><b>{CLEVER_NODE_GUIDE[m.node][lang]}</b><span>{m.pairs} {ui.pairs}</span></div><div className="probe-ratio"><span>{ui.normal} {(m.controlMedianMs/1000).toFixed(1)}s</span><i><b style={{width:`${Math.min(100,Math.max(8,m.slowdownRatio*50))}%`}}/></i><span>{ui.efficientCalc} {(m.strategyMedianMs/1000).toFixed(1)}s</span></div><strong className={`probe-status ${m.status}`}>{probeStatusLabel(m.status)}</strong></article>)}</div></section>}

  {attempts.length>0&&<section className="analysis-section"><div className="analysis-section-head"><div><span className="eyebrow">{ui.strategy}</span><h2>{ui.habit}</h2><p>{ui.habitCopy}</p></div></div><div className="strategy-visual-list">{plan.strategyMetrics.map(m=>{const pct=m.attempts?Math.round(m.correct/m.attempts*100):0;const status=m.status==="mastered"?"good":m.status==="needs_accuracy"||m.status==="needs_fluency"?"watch":m.status==="monitor"?"monitor":"empty";return <article className={`strategy-visual-row ${status}`} key={m.strategy}><div className="strategy-title"><b>{STRATEGY_GUIDE[m.strategy][lang]}</b><span>{m.attempts} {ui.questions} · {ui.evidenceWord} {m.evidence}%</span></div><div className="strategy-bar"><i style={{width:`${pct}%`}}/></div><strong>{m.attempts?`${pct}%`:"—"}</strong><small>{m.attempts?`${(m.medianMs/1000).toFixed(1)}s`:ui.awaitSample}</small></article>})}</div></section>}
 </div>;
}
