"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { ExamProfile } from "@/lib/types";

type Lang="zh"|"en";
type GradeFilter="all"|"1-2"|"3-4"|"5-6"|"7-8"|"9-10"|"11+";
type CompetitionFilter="kangaroo"|"australian-amc"|"maa-amc"|"cemc";
type MaaStage="all"|"maa-amc8"|"maa-amc10"|"maa-amc12"|"maa-aime";
const GRADE_OPTIONS:GradeFilter[]=["all","1-2","3-4","5-6","7-8","9-10","11+"];
const COMPETITION_OPTIONS:CompetitionFilter[]=["kangaroo","australian-amc","maa-amc","cemc"];
const MAA_STAGES:{id:MaaStage;zh:string;en:string;descZh:string;descEn:string}[]=[{id:"maa-amc8",zh:"AMC 8",en:"AMC 8",descZh:"8年级及以下 · 25题 / 40分钟",descEn:"Grade 8 and below · 25 questions / 40 min"},{id:"maa-amc10",zh:"AMC 10",en:"AMC 10",descZh:"10年级及以下 · 25题 / 75分钟",descEn:"Grade 10 and below · 25 questions / 75 min"},{id:"maa-amc12",zh:"AMC 12",en:"AMC 12",descZh:"12年级及以下 · 25题 / 75分钟",descEn:"Grade 12 and below · 25 questions / 75 min"},{id:"maa-aime",zh:"AIME",en:"AIME",descZh:"AMC 10/12 晋级赛 · 15题整数填答 · 2027起8+7题双90分钟",descEn:"Invitational after AMC 10/12 · 15 integers · from 2027: 8+7 questions in two 90-minute parts"}];
const REGION_ZH:Record<string,string>={Austria:"奥地利",Germany:"德国",Portugal:"葡萄牙","Australia AMC":"澳洲 AMC"};

function gradeBucket(exam:ExamProfile):GradeFilter{
 if(exam.gradeBand)return exam.gradeBand;
 const g=(exam.gradesEn||exam.grades||"").replace(/\s/g,"").toLowerCase();
 if(g==="pre-a"||g==="grade2"||g.includes("1–2")||g.includes("1-2"))return"1-2";
 if(g.includes("3–4")||g.includes("3-4")||g==="grade3"||g==="grade4")return"3-4";
 if(g.includes("5–6")||g.includes("5-6"))return"5-6";
 if(g.includes("7–8")||g.includes("7-8"))return"7-8";
 if(g.includes("9–10")||g.includes("9-10")||g==="grade9")return"9-10";
 return"11+";
}
function regionName(region:string,lang:Lang){return lang==="zh"?(REGION_ZH[region]||region):region;}
function yearOf(exam:ExamProfile){return exam.year??0;}
function competitionOf(exam:ExamProfile):CompetitionFilter|null{return exam.competitionId||null;}

const UI={
 zh:{title1:"国际数学竞赛",title2:"仿真考试实验室",copy:"袋鼠数学、澳洲 AMC 与美国 MAA AMC 使用各自独立的赛制模板。真题、官方样题和智能组卷都继承对应的题量、计分、题型与时间规则。",admin:"我的学习报告",chooseCompetition:"选择竞赛",chooseCompetitionDesc:"先选竞赛，再选年级与赛制。智能组卷只从同一赛制模板内选题。",choose:"选择训练学段",chooseDesc:"不同赛区、组别或样题可能采用不同赛制，系统会分别处理。",all:"全部年级",questions:"题",minutes:"分钟",max:"满分",start:"开始考试",open:"进入",smart:"智能组卷",smartDesc:"严格按当前赛制模板选题，不跨赛区、不跨题量、不跨计分规则。",past:"历年真题",samples:"官方样题",practice:"官方专项训练",papers:"套",regions:"个来源",range:"年份",exams:"套试卷",items:"道题",smartReady:"可智能组卷",rules:"赛制"},
 en:{title1:"Math Competitions",title2:"Mock Exam Lab",copy:"Math Kangaroo, Australian AMC and MAA AMC use independent competition formats. Past papers, official samples and smart mocks inherit the exact question count, scoring, answer format and timing model of their format.",admin:"My learning report",chooseCompetition:"Choose a competition",chooseCompetitionDesc:"Choose the competition, grade and format first. Smart mocks only sample from papers using that exact format.",choose:"Choose a grade band",chooseDesc:"Different divisions, countries or sample sets may use different formats and are kept separate.",all:"All grades",questions:"questions",minutes:"min",max:"Max",start:"Start exam",open:"Open",smart:"Smart mock",smartDesc:"Generated strictly within one format; no mixing of country, question count, scoring or timing rules.",past:"Past papers",samples:"Official samples",practice:"Official practice sets",papers:"papers",regions:"sources",range:"Years",exams:"papers",items:"questions",smartReady:"Smart mock available",rules:"Format"},
} as const;

export default function HomeClient({exams}:{exams:ExamProfile[]}){
 const [lang,setLang]=useState<Lang>("zh"),[competition,setCompetition]=useState<CompetitionFilter>("kangaroo"),[grade,setGrade]=useState<GradeFilter>("all"),[region,setRegion]=useState("all"),[maaStage,setMaaStage]=useState<MaaStage>("all");
 const router=useRouter(),ui=UI[lang];
 const meta={kangaroo:{zh:"袋鼠数学",en:"Math Kangaroo",zhDesc:"按国家/年级保留真实赛制差异",enDesc:"Country- and grade-specific formats preserved"},"australian-amc":{zh:"澳洲 AMC（AMT）",en:"Australian AMC (AMT)",zhDesc:"正式 AMC + 官方 Pre-A 样题",enDesc:"Official Australian AMC + Pre-A samples"},"maa-amc":{zh:"美国 AMC（MAA）",en:"MAA American Mathematics Competitions",zhDesc:"AMC 8 / AMC 10 / AMC 12 / AIME 独立赛制",enDesc:"AMC 8 / AMC 10 / AMC 12 / AIME formats"},cemc:{zh:"加拿大 CEMC",en:"Waterloo CEMC",zhDesc:"Gauss / Pascal / Cayley / Fermat / Euclid",enDesc:"Gauss / Pascal / Cayley / Fermat / Euclid"}} as const;
 const label=(k:CompetitionFilter)=>lang==="zh"?meta[k].zh:meta[k].en,desc=(k:CompetitionFilter)=>lang==="zh"?meta[k].zhDesc:meta[k].enDesc;
 const all=exams.filter(x=>competitionOf(x)===competition),official=all.filter(x=>x.paperType!=="smart"),smart=all.filter(x=>x.paperType==="smart");
 const maaMatch=(x:ExamProfile,stage:MaaStage)=>stage==="maa-aime"?Boolean(x.formatId?.startsWith("maa-aime")):x.formatId===stage;
 const selectedOfficial=competition==="maa-amc"?(maaStage==="all"?[]:official.filter(x=>maaMatch(x,maaStage))):(grade==="all"?[]:official.filter(x=>gradeBucket(x)===grade)),selectedSmart=competition==="maa-amc"?(maaStage==="all"?[]:smart.filter(x=>maaMatch(x,maaStage))):(grade==="all"?[]:smart.filter(x=>gradeBucket(x)===grade));
 const past=selectedOfficial.filter(x=>x.paperType!=="sample"&&x.paperType!=="practice"),samples=selectedOfficial.filter(x=>x.paperType==="sample"),practice=selectedOfficial.filter(x=>x.paperType==="practice");
 const availableRegions=competition==="kangaroo"?[...new Set(past.map(x=>x.country||""))].filter(Boolean).sort():[];
 const visiblePast=past.filter(x=>competition!=="kangaroo"||region==="all"||(x.country||"")===region),groups=competition==="kangaroo"?[...new Set(visiblePast.map(x=>x.country||""))].filter(Boolean).sort():[];
 const totalQuestions=official.reduce((s,x)=>s+x.questionCount,0);
 const selectionAll=competition==="maa-amc"?maaStage==="all":grade==="all";
 const gradeLabel=(g:GradeFilter)=>g==="all"?ui.all:g==="11+"?(lang==="zh"?"11–13年级":"Grades 11–13"):(lang==="zh"?`${g}年级`:`Grades ${g}`);
 const timing=(e:ExamProfile)=>e.timingMode==="untimed"?(lang==="zh"?"不限时":"Untimed"):e.timingMode==="recommended"?(lang==="zh"?`建议 ${Math.round(e.durationSeconds/60)} 分钟`:`Suggested ${Math.round(e.durationSeconds/60)} min`):`${Math.round(e.durationSeconds/60)} ${ui.minutes}`;
 const startExam=(e:ExamProfile,event:React.MouseEvent)=>router.push(e.paperType==="smart"?`/exam/${e.id}--${Math.floor(event.timeStamp*1000).toString(36)}`:`/exam/${e.id}`);
 const card=(e:ExamProfile,isSmart=false)=>{const name=lang==="zh"?(e.nameZh||e.name):(e.nameEn||e.name),source=lang==="zh"?(e.sourceLabelZh||e.sourceLabel):(e.sourceLabelEn||e.sourceLabel),format=lang==="zh"?(e.formatLabelZh||""):(e.formatLabelEn||""),rules=lang==="zh"?(e.rulesSummaryZh||""):(e.rulesSummaryEn||"");return <article key={e.id} className={isSmart?"smart-mock-card":""}><div className="feature-index">{format||label(competition)}</div><h2>{name}</h2><p><strong>{e.questionCount}</strong> {ui.questions} · {timing(e)} · {ui.max} {e.maxScore}</p>{rules&&<p><b>{ui.rules}：</b>{rules}</p>}{source&&<p>{source}</p>}<button className="primary-button" onClick={ev=>startExam(e,ev)}>{e.paperType==="practice"?(lang==="zh"?"开始训练":"Start practice"):ui.start}</button></article>};
 return <div className="home-shell">
  <section className="hero-card"><div className="eyebrow">COMPETITION FORMAT LAB</div><div className="hero-actions" style={{float:"right"}}><button className="secondary-button" onClick={()=>setLang(x=>x==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中"}</button></div><h1>{ui.title1}<br/><span>{ui.title2}</span></h1><p className="hero-copy">{ui.copy}</p><div className="hero-actions"><Link className="secondary-button" href="/student">{ui.admin}</Link></div></section>
  <section className="section-heading competition-heading"><div><span className="eyebrow">COMPETITIONS</span><h1>{ui.chooseCompetition}</h1><p>{ui.chooseCompetitionDesc}</p></div></section>
  <section className="competition-grid">{COMPETITION_OPTIONS.filter(k=>exams.some(x=>competitionOf(x)===k)).map(k=>{const set=exams.filter(x=>competitionOf(x)===k&&x.paperType!=="smart"),sm=exams.filter(x=>competitionOf(x)===k&&x.paperType==="smart"),years=set.map(yearOf).filter(Boolean);return <button key={k} className={`competition-card ${competition===k?"active":""}`} onClick={()=>{setCompetition(k);setGrade("all");setRegion("all");setMaaStage("all")}}><span>{k==="kangaroo"?"MK":k==="australian-amc"?"AMT":k==="maa-amc"?"MAA":"CEMC"}</span><strong>{label(k)}</strong><small>{desc(k)}</small><em>{set.length} {ui.papers}{sm.length?` · ${ui.smartReady}`:""}{years.length?` · ${Math.min(...years)}–${Math.max(...years)}`:""}</em></button>})}</section>
  {competition==="maa-amc"?<><section className="section-heading"><div><span className="eyebrow">MAA AMC PATHWAY</span><h1>{lang==="zh"?"选择赛事阶段":"Choose a competition stage"}</h1><p>{lang==="zh"?"AMC 8、AMC 10、AMC 12 与 AIME 使用独立赛制；不会用年级标签混在一起。":"AMC 8, AMC 10, AMC 12 and AIME use separate formats."}</p></div></section><div className="segmented" style={{marginBottom:28,flexWrap:"wrap"}}><button className={maaStage==="all"?"active":""} onClick={()=>setMaaStage("all")}>{lang==="zh"?"全部阶段":"All stages"}</button>{MAA_STAGES.map(st=>{const enabled=official.some(x=>maaMatch(x,st.id))||smart.some(x=>maaMatch(x,st.id));return <button key={st.id} disabled={!enabled} className={maaStage===st.id?"active":""} onClick={()=>setMaaStage(st.id)}>{lang==="zh"?st.zh:st.en}</button>})}</div></>:<><section className="section-heading"><div><span className="eyebrow">GRADE BANDS · {label(competition)}</span><h1>{ui.choose}</h1><p>{ui.chooseDesc}</p></div></section><div className="segmented" style={{marginBottom:28,flexWrap:"wrap"}}>{GRADE_OPTIONS.map(g=><button key={g} disabled={g!=="all"&&!all.some(x=>gradeBucket(x)===g)} className={grade===g?"active":""} onClick={()=>{setGrade(g);setRegion("all")}}>{gradeLabel(g)}</button>)}</div></>}
  {selectionAll?<section className="feature-grid">{competition==="maa-amc"?MAA_STAGES.map(st=>{const papers=official.filter(x=>maaMatch(x,st.id)),sm=smart.filter(x=>maaMatch(x,st.id)),years=papers.map(yearOf).filter(Boolean),enabled=papers.length>0||sm.length>0;const practiceCount=papers.filter(x=>x.paperType==="practice").length,fullCount=papers.length-practiceCount;return <article key={st.id}><div className="feature-index">MAA AMC</div><h2>{lang==="zh"?st.zh:st.en}</h2><p>{lang==="zh"?st.descZh:st.descEn}</p><p>{lang==="zh"?<><strong>{fullCount}</strong> 套完整卷 / 样题 · <strong>{practiceCount}</strong> 套官方专项</>:<><strong>{fullCount}</strong> full paper/sample · <strong>{practiceCount}</strong> official practice sets</>}{sm.length?` · ${ui.smartReady}`:""}</p><p>{fullCount>0&&years.length?`${ui.range} ${Math.min(...years)}–${Math.max(...years)}`:practiceCount>0?(lang==="zh"?"可进行官方专项训练 · 完整历年卷等待官方公开/授权资料":"Official practice available · full archives await official/licensed sources"):(lang==="zh"?"赛制已建 · 待导入官方/授权资料":"Format ready · awaiting official/licensed materials")}</p><button className="primary-button" disabled={!enabled} onClick={()=>setMaaStage(st.id)}>{enabled?ui.open:(lang==="zh"?"待导入":"Pending")}</button></article>}):GRADE_OPTIONS.filter(g=>g!=="all").map(g=>{const papers=official.filter(x=>gradeBucket(x)===g),sm=smart.filter(x=>gradeBucket(x)===g);if(!papers.length&&!sm.length)return null;const years=papers.map(yearOf).filter(Boolean),formats=[...new Set([...papers,...sm].map(x=>x.formatId).filter(Boolean))];return <article key={g}><div className="feature-index">{label(competition)}</div><h2>{gradeLabel(g)}</h2><p><strong>{papers.length}</strong> {ui.papers} · {formats.length} {lang==="zh"?"种赛制":"formats"}{sm.length?` · ${ui.smartReady}`:""}</p><p>{years.length?`${ui.range} ${Math.min(...years)}–${Math.max(...years)}`:""}</p><button className="primary-button" onClick={()=>setGrade(g)}>{ui.open}</button></article>})}</section>:<>
   {selectedSmart.length>0&&<><section className="section-heading smart-heading" style={{marginTop:42}}><div><span className="eyebrow">SMART BY FORMAT</span><h1>{ui.smart}</h1><p>{ui.smartDesc}</p></div></section><section className="feature-grid smart-mock-grid">{selectedSmart.map(x=>card(x,true))}</section></>}
   {samples.length>0&&<><section className="section-heading" style={{marginTop:48}}><div><span className="eyebrow">OFFICIAL SAMPLES</span><h1>{ui.samples}</h1></div></section><section className="feature-grid">{samples.map(x=>card(x))}</section></>}
   {practice.length>0&&<><section className="section-heading" style={{marginTop:48}}><div><span className="eyebrow">OFFICIAL PRACTICE</span><h1>{ui.practice}</h1><p>{lang==="zh"?"MAA Programs 官方发布的专题练习集；不限时训练，不计入历年真题，也不参与正式智能模拟组卷。":"Official topic practice sets published by MAA Programs; untimed, separate from past papers and official smart mocks."}</p></div></section><section className="feature-grid">{practice.sort((a,b)=>(a.name||"").localeCompare(b.name||"")).map(x=>card(x))}</section></>}
   {past.length>0&&<><section className="section-heading" style={{marginTop:48}}><div><span className="eyebrow">PAST PAPERS</span><h1>{ui.past}</h1></div></section>{competition==="kangaroo"&&<div className="segmented" style={{marginBottom:24,flexWrap:"wrap"}}><button className={region==="all"?"active":""} onClick={()=>setRegion("all")}>{lang==="zh"?"全部赛区":"All formats"}</button>{availableRegions.map(r=><button key={r} className={region===r?"active":""} onClick={()=>setRegion(r)}>{regionName(r,lang)}</button>)}</div>}{competition==="kangaroo"?groups.map(r=><section key={r}><div className="section-heading" style={{marginTop:28,marginBottom:8}}><div><span className="eyebrow">{regionName(r,lang)}</span></div></div><div className="feature-grid">{visiblePast.filter(x=>(x.country||"")===r).sort((a,b)=>yearOf(b)-yearOf(a)||a.id.localeCompare(b.id)).map(x=>card(x))}</div></section>):<section className="feature-grid">{visiblePast.sort((a,b)=>yearOf(b)-yearOf(a)||a.id.localeCompare(b.id)).map(x=>card(x))}</section>}</>}
  </>}
  <section className="stat-grid"><article><strong>{official.length}</strong><span>{ui.exams}</span><p>{label(competition)}</p></article><article><strong>{totalQuestions}</strong><span>{ui.items}</span><p>{lang==="zh"?"当前竞赛已校验题量":"Verified questions in this competition"}</p></article><article><strong>{[...new Set(all.map(x=>x.formatId).filter(Boolean))].length}</strong><span>{lang==="zh"?"种赛制模板":"formats"}</span><p>{lang==="zh"?"题量、计分、题型与时间分别继承":"Question count, scoring, answer type and timing are inherited"}</p></article><article><strong>{smart.length}</strong><span>{ui.smart}</span><p>{ui.smartDesc}</p></article></section>
 </div>;
}
