"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";

export default function ParentRegisterClient(){
 const router=useRouter(),[step,setStep]=useState<"form"|"verify">("form"),[email,setEmail]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[registrationEnabled,setRegistrationEnabled]=useState<boolean|null>(null);
 useEffect(()=>{fetch("/api/auth/parent/status").then(async r=>(await r.json()).registrationEnabled===true).then(setRegistrationEnabled).catch(()=>setRegistrationEnabled(false))},[]);
 async function start(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const body={name:fd.get("name"),email:fd.get("email"),password:fd.get("password"),acceptedTerms:fd.get("acceptedTerms")==="on",guardianConfirmed:fd.get("guardianConfirmed")==="on"};try{const r=await fetch("/api/auth/parent/register/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),x=await r.json();if(!r.ok)throw new Error(x.error||"发送验证码失败");setEmail(String(body.email||""));setStep("verify")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const r=await fetch("/api/auth/parent/register/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,code:fd.get("code")})}),x=await r.json();if(!r.ok)throw new Error(x.error||"验证失败");router.replace("/parent");router.refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="login-shell"><div className="login-card"><span className="eyebrow">PARENT ACCOUNT</span><h1>{step==="form"?"创建家长账号":"验证邮箱"}</h1>{registrationEnabled===false&&step==="form"&&<div className="warning-box">邮箱注册服务正在配置中。现有学生账号仍可正常登录使用。</div>}{step==="form"?<form onSubmit={start} className="parent-auth-form"><label>家长姓名<input name="name" required maxLength={60}/></label><label>邮箱<input name="email" type="email" required autoComplete="email"/></label><label>密码<input name="password" type="password" required minLength={8} autoComplete="new-password"/></label><label className="check-line"><input name="guardianConfirmed" type="checkbox" required/>我确认自己是该学生的监护人或成年负责人</label><label className="check-line"><input name="acceptedTerms" type="checkbox" required/><span>我同意 <Link href="/terms" target="_blank">用户协议</Link> 和 <Link href="/privacy" target="_blank">隐私政策</Link></span></label><button className="primary-button" disabled={busy||registrationEnabled!==true}>{registrationEnabled===null?"正在检查邮箱服务…":busy?"正在发送…":"发送邮箱验证码"}</button></form>:<form onSubmit={verify} className="parent-auth-form"><p>验证码已发送到 <b>{email}</b>，10分钟内有效。</p><label>6位验证码<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required autoFocus/></label><button className="primary-button" disabled={busy}>{busy?"正在验证…":"验证并创建账号"}</button><button type="button" className="secondary-button" onClick={()=>setStep("form")}>返回修改邮箱</button></form>}{error&&<div className="login-error">{error}</div>}<p className="auth-switch">已有家长账号？ <Link href="/parent/login">直接登录</Link></p><p className="auth-switch">学生本人？ <Link href="/login">学生 PIN 登录</Link></p></div></div>
}
