"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
export default function ParentLoginClient(){
 const router=useRouter(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reset,setReset]=useState(false),[email,setEmail]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const r=await fetch("/api/auth/parent/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})}),x=await r.json();if(!r.ok)throw new Error(x.error||"登录失败");router.replace("/parent");router.refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function forgot(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget),mail=String(fd.get("email")||"");try{const r=await fetch("/api/auth/parent/password/forgot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:mail})}),x=await r.json();if(!r.ok)throw new Error(x.error||"发送失败");setEmail(mail);setReset(true)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function doReset(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const r=await fetch("/api/auth/parent/password/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,code:fd.get("code"),password:fd.get("password")})}),x=await r.json();if(!r.ok)throw new Error(x.error||"重置失败");setReset(false);setError("密码已重置，请使用新密码登录。")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="login-shell"><div className="login-card"><span className="eyebrow">PARENT LOGIN</span><h1>家长账号</h1>{!reset?<><form onSubmit={submit} className="parent-auth-form"><label>邮箱<input name="email" type="email" required autoComplete="email"/></label><label>密码<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary-button" disabled={busy}>{busy?"正在登录…":"登录家长中心"}</button></form><form onSubmit={forgot} className="forgot-inline"><input name="email" type="email" required placeholder="忘记密码？输入注册邮箱"/><button className="secondary-button" disabled={busy}>发送重置码</button></form></>:<form onSubmit={doReset} className="parent-auth-form"><p>重置验证码已发送到 <b>{email}</b>。</p><label>6位验证码<input name="code" inputMode="numeric" pattern="[0-9]{6}" required/></label><label>新密码<input name="password" type="password" minLength={8} required/></label><button className="primary-button" disabled={busy}>重置密码</button></form>}{error&&<div className={error.startsWith("密码已重置")?"success-box":"login-error"}>{error}</div>}<p className="auth-switch">还没有账号？ <Link href="/parent/register">邮箱注册</Link></p><p className="auth-switch">学生本人？ <Link href="/login">学生 PIN 登录</Link></p></div></div>
}
