"use client";
import Link from "next/link";
import {useMemo,useRef,useState} from "react";
import {generateArithmeticSet} from "@/lib/arithmetic-generator";
import type {ArithmeticGrade} from "@/lib/arithmetic";
import {arithmeticItemToEntity,buildStructureDiscoveryTask,type LearnerSignal} from "@/lib/math-engine";

export default function StructureDiscoveryClient({grade}:{grade:ArithmeticGrade}){
 const items=useMemo(()=>generateArithmeticSet(grade,48,Math.floor(Date.now()/60000)),[grade]);
 const tasks=useMemo(()=>items.map(x=>buildStructureDiscoveryTask(arithmeticItemToEntity(x))).filter(x=>x.choices.length>=2&&x.choices.some(c=>c.preferred)).slice(0,12),[items]);
 const [idx,setIdx]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [done,setDone]=useState(0);const [preferred,setPreferred]=useState(0);const [saving,setSaving]=useState(false);const [finished,setFinished]=useState(false);const shownAt=useRef(performance.now());
 const task=tasks[idx];
 if(!task)return <div className="mental-shell"><section className="mental-card discovery-empty"><span className="eyebrow">结构发现 · {grade}年级</span><h1>这一轮没有合适的结构题</h1><p>系统不会拿普通计算题冒充“结构发现”。请返回训练中心重新生成。</p><Link className="primary-button" href="/arithmetic">返回训练中心</Link></section></div>;
 const choose=async(id:string)=>{if(selected)return;setSelected(id);const choice=task.choices.find(x=>x.id===id)!;const latency=Math.max(1,performance.now()-shownAt.current);const signal:LearnerSignal={entityId:task.id.replace(/^discovery:/,""),grade,strategyId:task.strategyIds[0],stage:choice.preferred?"recognized":"unknown",correct:choice.valid,efficient:choice.preferred,latencyMs:latency,hintLevel:0,transformations:[],timestamp:Date.now()};setSaving(true);try{await fetch('/api/math-engine/signals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({signal,source:'structure_discovery'})})}finally{setSaving(false)};setDone(x=>x+1);if(choice.preferred)setPreferred(x=>x+1)};
 const next=()=>{if(idx>=tasks.length-1){setFinished(true);return}setIdx(x=>x+1);setSelected(null);shownAt.current=performance.now()};
 if(finished)return <div className="report-shell"><section className="score-hero"><div><span className="eyebrow">结构发现训练</span><h1>这一轮完成</h1><p>这里测的是“是否主动换到更有利的表示”，不是单纯答案对错。</p></div><div className="score-ring"><strong>{preferred}</strong><span>/ {done}</span><small>主动换结构</small></div></section><div className="report-actions"><Link className="primary-button" href={`/arithmetic/discovery/${grade}`}>再来一轮</Link><Link className="secondary-button" href="/arithmetic">返回训练中心</Link></div></div>;
 return <div className="mental-shell"><section className="mental-topbar"><div><span className="eyebrow">结构发现 · {grade}年级</span><strong>先别算</strong></div><div className="mental-progress"><span>{idx+1}</span> / {tasks.length}</div><Link className="ghost-button" href="/arithmetic">退出</Link></section><section className="mental-card"><div className="mental-meta"><div><span>{task.questionZh}</span><small>先观察关系，不急着求答案</small></div><b>目标：找出更省力的表示</b></div><div className="mental-prompt">{task.prompt}</div><div className="discovery-choices">{task.choices.map((c,i)=><button key={c.id} type="button" disabled={Boolean(selected)||saving} className={`discovery-choice ${selected===c.id?(c.preferred?'preferred':'direct-choice'):''}`} onClick={()=>void choose(c.id)}><span className="discovery-choice-index">{String.fromCharCode(65+i)}</span><div><strong>{c.label}</strong>{selected===c.id&&<small>{c.note}</small>}</div></button>)}</div>{selected&&<div className="coaching-panel"><b>{task.choices.find(x=>x.id===selected)?.preferred?'你主动换到了更有利的表示':'这个表示当然合法，但还没有利用结构'}</b><p>{task.choices.find(x=>x.id===selected)?.note}</p><button className="primary-button" onClick={next} disabled={saving}>{idx>=tasks.length-1?'完成本轮':'下一题'}</button></div>}<div className="mental-hint">这里不要求先算出答案。系统记录你第一眼有没有发现更省力的数学结构。</div></section></div>;
}
