import assert from "node:assert/strict";
import { publicAccessCatalog } from "../src/lib/access-catalog";
import { ACCESS_POLICY_VERSION } from "../src/lib/access-policy";
const catalog=publicAccessCatalog();
assert.equal(catalog.version,ACCESS_POLICY_VERSION);
assert.equal(catalog.checkoutAvailable,false);
assert.deepEqual(catalog.plans.map(p=>p.id),["guest","free","plus","pro"]);
assert.ok(catalog.plans.every(p=>p.checkoutAvailable===false));
const find=(id:string)=>catalog.features.find(f=>f.id===id)?.tiers;
assert.equal(find("public_sample_exam")?.guest,true);
assert.equal(find("arithmetic_basic")?.guest,true);
assert.equal(find("exam_premium")?.guest,false);
assert.equal(find("exam_premium")?.free,false);
assert.equal(find("exam_premium")?.plus,true);
assert.equal(find("exam_premium")?.pro,true);
assert.equal(find("report_basic")?.free,true);
assert.equal(find("family_dashboard")?.guest,false);
assert.equal(find("family_dashboard")?.free,true);
assert.equal(find("solution_ai")?.free,false);
assert.equal(find("solution_ai")?.pro,true);
assert.ok(catalog.features.every(f=>Object.keys(f.tiers).length===4));
console.log("ACCESS_CATALOG_PASS",catalog.version,catalog.features.length,"features; checkout disabled");
